const COUNTRIES = [
	{
		name: 'Afghanistan',
		code: 'AF',
		languages: ['pus', 'prd', 'tuk'],
		flag: '🇦🇫',
	},
	{
		name: 'Aland',
		code: 'AX',
		languages: ['swe'],
		flag: '🇦🇽',
	},
	{
		name: 'Albania',
		code: 'AL',
		languages: ['sqi'],
		flag: '🇦🇱',
	},
	{
		name: 'Algeria',
		code: 'DZ',
		languages: ['ara'],
		flag: '🇩🇿',
	},
	{
		name: 'American Samoa',
		code: 'AS',
		languages: ['eng', 'smo'],
		flag: '🇦🇸',
	},
	{
		name: 'Andorra',
		code: 'AD',
		languages: ['cat'],
		flag: '🇦🇩',
	},
	{
		name: 'Angola',
		code: 'AO',
		languages: ['por'],
		flag: '🇦🇴',
	},
	{
		name: 'Anguilla',
		code: 'AI',
		languages: ['eng'],
		flag: '🇦🇮',
	},
	{
		name: 'Antarctica',
		code: 'AQ',
		languages: ['eng'],
		flag: '🇦🇶',
	},
	{
		name: 'Antigua and Barbuda',
		code: 'AG',
		languages: ['eng'],
		flag: '🇦🇬',
	},
	{
		name: 'Argentina',
		code: 'AR',
		languages: ['grn', 'spa'],
		flag: '🇦🇷',
	},
	{
		name: 'Armenia',
		code: 'AM',
		languages: ['hye'],
		flag: '🇦🇲',
	},
	{
		name: 'Aruba',
		code: 'AW',
		languages: ['nld', 'pap'],
		flag: '🇦🇼',
	},
	{
		name: 'Australia',
		code: 'AU',
		languages: ['eng'],
		flag: '🇦🇺',
	},
	{
		name: 'Austria',
		code: 'AT',
		languages: ['deu'],
		flag: '🇦🇹',
	},
	{
		name: 'Azerbaijan',
		code: 'AZ',
		languages: ['aze', 'rus'],
		flag: '🇦🇿',
	},
	{
		name: 'Bahamas',
		code: 'BS',
		languages: ['eng'],
		flag: '🇧🇸',
	},
	{
		name: 'Bahrain',
		code: 'BH',
		languages: ['ara'],
		flag: '🇧🇭',
	},
	{
		name: 'Bangladesh',
		code: 'BD',
		languages: ['ben'],
		flag: '🇧🇩',
	},
	{
		name: 'Barbados',
		code: 'BB',
		languages: ['eng'],
		flag: '🇧🇧',
	},
	{
		name: 'Belarus',
		code: 'BY',
		languages: ['bel', 'rus'],
		flag: '🇧🇾',
	},
	{
		name: 'Belgium',
		code: 'BE',
		languages: ['deu', 'fra', 'nld'],
		flag: '🇧🇪',
	},
	{
		name: 'Belize',
		code: 'BZ',
		languages: ['bjz', 'eng', 'spa'],
		flag: '🇧🇿',
	},
	{
		name: 'Benin',
		code: 'BJ',
		languages: ['fra'],
		flag: '🇧🇯',
	},
	{
		name: 'Bermuda',
		code: 'BM',
		languages: ['eng'],
		flag: '🇧🇲',
	},
	{
		name: 'Bhutan',
		code: 'BT',
		languages: ['dzo'],
		flag: '🇧🇹',
	},
	{
		name: 'Bolivia',
		code: 'BO',
		languages: ['aym', 'grn', 'que', 'spa'],
		flag: '🇧🇴',
	},
	{
		name: 'Bonaire',
		code: 'BQ',
		languages: ['eng', 'nld', 'pap'],
		flag: '🇧🇶',
	},
	{
		name: 'Bosnia and Herzegovina',
		code: 'BA',
		languages: ['bos', 'hrv', 'srp'],
		flag: '🇧🇦',
	},
	{
		name: 'Botswana',
		code: 'BW',
		languages: ['eng', 'tsn'],
		flag: '🇧🇼',
	},
	{
		name: 'Bouvet Island',
		code: 'BV',
		languages: ['nor'],
		flag: '🇧🇻',
	},
	{
		name: 'Brazil',
		code: 'BR',
		languages: ['por'],
		flag: '🇧🇷',
	},
	{
		name: 'British Indian Ocean Territory',
		code: 'IO',
		languages: ['eng'],
		flag: '🇮🇴',
	},
	{
		name: 'British Virgin Islands',
		code: 'VG',
		languages: ['eng'],
		flag: '🇻🇬',
	},
	{
		name: 'Brunei',
		code: 'BN',
		languages: ['msa'],
		flag: '🇧🇳',
	},
	{
		name: 'Bulgaria',
		code: 'BG',
		languages: ['bul'],
		flag: '🇧🇬',
	},
	{
		name: 'Burkina Faso',
		code: 'BF',
		languages: ['fra'],
		flag: '🇧🇫',
	},
	{
		name: 'Burundi',
		code: 'BI',
		languages: ['fra', 'run'],
		flag: '🇧🇮',
	},
	{
		name: 'Cambodia',
		code: 'KH',
		languages: ['khm'],
		flag: '🇰🇭',
	},
	{
		name: 'Cameroon',
		code: 'CM',
		languages: ['eng', 'fra'],
		flag: '🇨🇲',
	},
	{
		name: 'Canada',
		code: 'CA',
		languages: ['eng', 'fra'],
		flag: '🇨🇦',
	},
	{
		name: 'Cape Verde',
		code: 'CV',
		languages: ['por'],
		flag: '🇨🇻',
	},
	{
		name: 'Cayman Islands',
		code: 'KY',
		languages: ['eng'],
		flag: '🇰🇾',
	},
	{
		name: 'Central African Republic',
		code: 'CF',
		languages: ['fra', 'sag'],
		flag: '🇨🇫',
	},
	{
		name: 'Chad',
		code: 'TD',
		languages: ['ara', 'fra'],
		flag: '🇹🇩',
	},
	{
		name: 'Chile',
		code: 'CL',
		languages: ['spa'],
		flag: '🇨🇱',
	},
	{
		name: 'China',
		code: 'CN',
		languages: ['zho'],
		flag: '🇨🇳',
	},
	{
		name: 'Christmas Island',
		code: 'CX',
		languages: ['eng'],
		flag: '🇨🇽',
	},
	{
		name: 'Cocos (Keeling) Islands',
		code: 'CC',
		languages: ['eng'],
		flag: '🇨🇨',
	},
	{
		name: 'Colombia',
		code: 'CO',
		languages: ['spa'],
		flag: '🇨🇴',
	},
	{
		name: 'Comoros',
		code: 'KM',
		languages: ['ara', 'fra', 'zdj'],
		flag: '🇰🇲',
	},
	{
		name: 'Cook Islands',
		code: 'CK',
		languages: ['eng', 'rar'],
		flag: '🇨🇰',
	},
	{
		name: 'Costa Rica',
		code: 'CR',
		languages: ['spa'],
		flag: '🇨🇷',
	},
	{
		name: 'Croatia',
		code: 'HR',
		languages: ['hrv'],
		flag: '🇭🇷',
	},
	{
		name: 'Cuba',
		code: 'CU',
		languages: ['spa'],
		flag: '🇨🇺',
	},
	{
		name: 'Curacao',
		code: 'CW',
		languages: ['eng', 'nld', 'pap'],
		flag: '🇨🇼',
	},
	{
		name: 'Cyprus',
		code: 'CY',
		languages: ['ell', 'tur'],
		flag: '🇨🇾',
	},
	{
		name: 'Czech Republic',
		code: 'CZ',
		languages: ['ces', 'slk'],
		flag: '🇨🇿',
	},
	{
		name: 'Democratic Republic of the Congo',
		code: 'CD',
		languages: ['fra', 'kon', 'lin', 'lua', 'swa'],
		flag: '🇨🇩',
	},
	{
		name: 'Denmark',
		code: 'DK',
		languages: ['dan'],
		flag: '🇩🇰',
	},
	{
		name: 'Djibouti',
		code: 'DJ',
		languages: ['ara', 'fra'],
		flag: '🇩🇯',
	},
	{
		name: 'Dominica',
		code: 'DM',
		languages: ['eng'],
		flag: '🇩🇲',
	},
	{
		name: 'Dominican Republic',
		code: 'DO',
		languages: ['spa'],
		flag: '🇩🇴',
	},
	{
		name: 'East Timor',
		code: 'TL',
		languages: ['por', 'tet'],
		flag: '🇹🇱',
	},
	{
		name: 'Ecuador',
		code: 'EC',
		languages: ['spa'],
		flag: '🇪🇨',
	},
	{
		name: 'Egypt',
		code: 'EG',
		languages: ['ara'],
		flag: '🇪🇬',
	},
	{
		name: 'El Salvador',
		code: 'SV',
		languages: ['spa'],
		flag: '🇸🇻',
	},
	{
		name: 'Equatorial Guinea',
		code: 'GQ',
		languages: ['fra', 'por', 'spa'],
		flag: '🇬🇶',
	},
	{
		name: 'Eritrea',
		code: 'ER',
		languages: ['ara', 'eng', 'tir'],
		flag: '🇪🇷',
	},
	{
		name: 'Estonia',
		code: 'EE',
		languages: ['est'],
		flag: '🇪🇪',
	},
	{
		name: 'Ethiopia',
		code: 'ET',
		languages: ['amh'],
		flag: '🇪🇹',
	},
	{
		name: 'Falkland Islands',
		code: 'FK',
		languages: ['eng'],
		flag: '🇫🇰',
	},
	{
		name: 'Faroe Islands',
		code: 'FO',
		languages: ['dan', 'fao'],
		flag: '🇫🇴',
	},
	{
		name: 'Fiji',
		code: 'FJ',
		languages: ['eng', 'fij', 'hif'],
		flag: '🇫🇯',
	},
	{
		name: 'Finland',
		code: 'FI',
		languages: ['fin', 'swe'],
		flag: '🇫🇮',
	},
	{
		name: 'France',
		code: 'FR',
		languages: ['fra'],
		flag: '🇫🇷',
	},
	{
		name: 'French Guiana',
		code: 'GF',
		languages: ['fra'],
		flag: '🇬🇫',
	},
	{
		name: 'French Polynesia',
		code: 'PF',
		languages: ['fra'],
		flag: '🇵🇫',
	},
	{
		name: 'French Southern Territories',
		code: 'TF',
		languages: ['fra'],
		flag: '🇹🇫',
	},
	{
		name: 'Gabon',
		code: 'GA',
		languages: ['fra'],
		flag: '🇬🇦',
	},
	{
		name: 'Gambia',
		code: 'GM',
		languages: ['eng'],
		flag: '🇬🇲',
	},
	{
		name: 'Georgia',
		code: 'GE',
		languages: ['kat'],
		flag: '🇬🇪',
	},
	{
		name: 'Germany',
		code: 'DE',
		languages: ['deu'],
		flag: '🇩🇪',
	},
	{
		name: 'Ghana',
		code: 'GH',
		languages: ['eng'],
		flag: '🇬🇭',
	},
	{
		name: 'Gibraltar',
		code: 'GI',
		languages: ['eng'],
		flag: '🇬🇮',
	},
	{
		name: 'Greece',
		code: 'GR',
		languages: ['ell'],
		flag: '🇬🇷',
	},
	{
		name: 'Greenland',
		code: 'GL',
		languages: ['kal'],
		flag: '🇬🇱',
	},
	{
		name: 'Grenada',
		code: 'GD',
		languages: ['eng'],
		flag: '🇬🇩',
	},
	{
		name: 'Guadeloupe',
		code: 'GP',
		languages: ['fra'],
		flag: '🇬🇵',
	},
	{
		name: 'Guam',
		code: 'GU',
		languages: ['cha', 'eng', 'spa'],
		flag: '🇬🇺',
	},
	{
		name: 'Guatemala',
		code: 'GT',
		languages: ['spa'],
		flag: '🇬🇹',
	},
	{
		name: 'Guernsey',
		code: 'GG',
		languages: ['eng', 'fra', 'nfr'],
		flag: '🇬🇬',
	},
	{
		name: 'Guinea',
		code: 'GN',
		languages: ['fra'],
		flag: '🇬🇳',
	},
	{
		name: 'Guinea-Bissau',
		code: 'GW',
		languages: ['por', 'pov'],
		flag: '🇬🇼',
	},
	{
		name: 'Guyana',
		code: 'GY',
		languages: ['eng'],
		flag: '🇬🇾',
	},
	{
		name: 'Haiti',
		code: 'HT',
		languages: ['fra', 'hat'],
		flag: '🇭🇹',
	},
	{
		name: 'Heard Island and McDonald Islands',
		code: 'HM',
		languages: ['eng'],
		flag: '🇭🇲',
	},
	{
		name: 'Honduras',
		code: 'HN',
		languages: ['spa'],
		flag: '🇭🇳',
	},
	{
		name: 'Hong Kong',
		code: 'HK',
		languages: ['eng', 'zho'],
		flag: '🇭🇰',
	},
	{
		name: 'Hungary',
		code: 'HU',
		languages: ['hun'],
		flag: '🇭🇺',
	},
	{
		name: 'Iceland',
		code: 'IS',
		languages: ['isl'],
		flag: '🇮🇸',
	},
	{
		name: 'India',
		code: 'IN',
		languages: ['eng', 'hin', 'tam'],
		flag: '🇮🇳',
	},
	{
		name: 'Indonesia',
		code: 'ID',
		languages: ['ind'],
		flag: '🇮🇩',
	},
	{
		name: 'Iran',
		code: 'IR',
		languages: ['fas'],
		flag: '🇮🇷',
	},
	{
		name: 'Iraq',
		code: 'IQ',
		languages: ['ara', 'arc', 'ckb'],
		flag: '🇮🇶',
	},
	{
		name: 'Ireland',
		code: 'IE',
		languages: ['eng', 'gle'],
		flag: '🇮🇪',
	},
	{
		name: 'Isle of Man',
		code: 'IM',
		languages: ['eng', 'glv'],
		flag: '🇮🇲',
	},
	{
		name: 'Israel',
		code: 'IL',
		languages: ['ara', 'heb'],
		flag: '🇮🇱',
	},
	{
		name: 'Italy',
		code: 'IT',
		languages: ['ita'],
		flag: '🇮🇹',
	},
	{
		name: 'Ivory Coast',
		code: 'CI',
		languages: ['fra'],
		flag: '🇨🇮',
	},
	{
		name: 'Jamaica',
		code: 'JM',
		languages: ['eng', 'jam'],
		flag: '🇯🇲',
	},
	{
		name: 'Japan',
		code: 'JP',
		languages: ['jpn'],
		flag: '🇯🇵',
	},
	{
		name: 'Jersey',
		code: 'JE',
		languages: ['eng', 'fra', 'nrf'],
		flag: '🇯🇪',
	},
	{
		name: 'Jordan',
		code: 'JO',
		languages: ['ara'],
		flag: '🇯🇴',
	},
	{
		name: 'Kazakhstan',
		code: 'KZ',
		languages: ['kaz', 'rus'],
		flag: '🇰🇿',
	},
	{
		name: 'Kenya',
		code: 'KE',
		languages: ['eng', 'swa'],
		flag: '🇰🇪',
	},
	{
		name: 'Kiribati',
		code: 'KI',
		languages: ['eng', 'gil'],
		flag: '🇰🇮',
	},
	{
		name: 'Kosovo',
		code: 'XK',
		languages: ['sqi', 'srp'],
		flag: '🇽🇰',
	},
	{
		name: 'Kuwait',
		code: 'KW',
		languages: ['ara'],
		flag: '🇰🇼',
	},
	{
		name: 'Kyrgyzstan',
		code: 'KG',
		languages: ['kir', 'rus'],
		flag: '🇰🇬',
	},
	{
		name: 'Laos',
		code: 'LA',
		languages: ['lao'],
		flag: '🇱🇦',
	},
	{
		name: 'Latvia',
		code: 'LV',
		languages: ['lav'],
		flag: '🇱🇻',
	},
	{
		name: 'Lebanon',
		code: 'LB',
		languages: ['ara', 'fra'],
		flag: '🇱🇧',
	},
	{
		name: 'Lesotho',
		code: 'LS',
		languages: ['eng', 'sot'],
		flag: '🇱🇸',
	},
	{
		name: 'Liberia',
		code: 'LR',
		languages: ['eng'],
		flag: '🇱🇷',
	},
	{
		name: 'Libya',
		code: 'LY',
		languages: ['ara'],
		flag: '🇱🇾',
	},
	{
		name: 'Liechtenstein',
		code: 'LI',
		languages: ['deu'],
		flag: '🇱🇮',
	},
	{
		name: 'Lithuania',
		code: 'LT',
		languages: ['lit'],
		flag: '🇱🇹',
	},
	{
		name: 'Luxembourg',
		code: 'LU',
		languages: ['deu', 'fra', 'ltz'],
		flag: '🇱🇺',
	},
	{
		name: 'Macao',
		code: 'MO',
		languages: ['por', 'zho'],
		flag: '🇲🇴',
	},
	{
		name: 'Madagascar',
		code: 'MG',
		languages: ['fra', 'mlg'],
		flag: '🇲🇬',
	},
	{
		name: 'Malawi',
		code: 'MW',
		languages: ['eng', 'nya'],
		flag: '🇲🇼',
	},
	{
		name: 'Malaysia',
		code: 'MY',
		languages: ['eng', 'msa'],
		flag: '🇲🇾',
	},
	{
		name: 'Maldives',
		code: 'MV',
		languages: ['div'],
		flag: '🇲🇻',
	},
	{
		name: 'Mali',
		code: 'ML',
		languages: ['fra'],
		flag: '🇲🇱',
	},
	{
		name: 'Malta',
		code: 'MT',
		languages: ['eng', 'mlt'],
		flag: '🇲🇹',
	},
	{
		name: 'Marshall Islands',
		code: 'MH',
		languages: ['eng', 'mah'],
		flag: '🇲🇭',
	},
	{
		name: 'Martinique',
		code: 'MQ',
		languages: ['fra'],
		flag: '🇲🇶',
	},
	{
		name: 'Mauritania',
		code: 'MR',
		languages: ['ara'],
		flag: '🇲🇷',
	},
	{
		name: 'Mauritius',
		code: 'MU',
		languages: ['eng', 'fra', 'mfe'],
		flag: '🇲🇺',
	},
	{
		name: 'Mayotte',
		code: 'YT',
		languages: ['fra'],
		flag: '🇾🇹',
	},
	{
		name: 'Mexico',
		code: 'MX',
		languages: ['spa'],
		flag: '🇲🇽',
	},
	{
		name: 'Micronesia',
		code: 'FM',
		languages: ['eng'],
		flag: '🇫🇲',
	},
	{
		name: 'Moldova',
		code: 'MD',
		languages: ['ron'],
		flag: '🇲🇩',
	},
	{
		name: 'Monaco',
		code: 'MC',
		languages: ['fra'],
		flag: '🇲🇨',
	},
	{
		name: 'Mongolia',
		code: 'MN',
		languages: ['mon'],
		flag: '🇲🇳',
	},
	{
		name: 'Montenegro',
		code: 'ME',
		languages: ['cnr', 'srp', 'bos', 'sqi', 'hrv'],
		flag: '🇲🇪',
	},
	{
		name: 'Montserrat',
		code: 'MS',
		languages: ['eng'],
		flag: '🇲🇸',
	},
	{
		name: 'Morocco',
		code: 'MA',
		languages: ['ara', 'zgh'],
		flag: '🇲🇦',
	},
	{
		name: 'Mozambique',
		code: 'MZ',
		languages: ['por'],
		flag: '🇲🇿',
	},
	{
		name: 'Myanmar',
		code: 'MM',
		languages: ['mya'],
		flag: '🇲🇲',
	},
	{
		name: 'Namibia',
		code: 'NA',
		languages: ['afr', 'deu', 'eng', 'her', 'hgm', 'kwn', 'loz', 'ndo', 'tsn'],
		flag: '🇳🇦',
	},
	{
		name: 'Nauru',
		code: 'NR',
		languages: ['eng', 'nau'],
		flag: '🇳🇷',
	},
	{
		name: 'Nepal',
		code: 'NP',
		languages: ['nep'],
		flag: '🇳🇵',
	},
	{
		name: 'Netherlands',
		code: 'NL',
		languages: ['nld'],
		flag: '🇳🇱',
	},
	{
		name: 'New Caledonia',
		code: 'NC',
		languages: ['fra'],
		flag: '🇳🇨',
	},
	{
		name: 'New Zealand',
		code: 'NZ',
		languages: ['eng', 'mri', 'nzs'],
		flag: '🇳🇿',
	},
	{
		name: 'Nicaragua',
		code: 'NI',
		languages: ['spa'],
		flag: '🇳🇮',
	},
	{
		name: 'Niger',
		code: 'NE',
		languages: ['fra'],
		flag: '🇳🇪',
	},
	{
		name: 'Nigeria',
		code: 'NG',
		languages: ['eng'],
		flag: '🇳🇬',
	},
	{
		name: 'Niue',
		code: 'NU',
		languages: ['eng', 'niu'],
		flag: '🇳🇺',
	},
	{
		name: 'Norfolk Island',
		code: 'NF',
		languages: ['eng', 'pih'],
		flag: '🇳🇫',
	},
	{
		name: 'North Korea',
		code: 'KP',
		languages: ['kor'],
		flag: '🇰🇵',
	},
	{
		name: 'North Macedonia',
		code: 'MK',
		languages: ['mkd'],
		flag: '🇲🇰',
	},
	{
		name: 'Northern Mariana Islands',
		code: 'MP',
		languages: ['cal', 'cha', 'eng'],
		flag: '🇲🇵',
	},
	{
		name: 'Norway',
		code: 'NO',
		languages: ['nor'],
		flag: '🇳🇴',
	},
	{
		name: 'Oman',
		code: 'OM',
		languages: ['ara'],
		flag: '🇴🇲',
	},
	{
		name: 'Pakistan',
		code: 'PK',
		languages: ['eng', 'urd'],
		flag: '🇵🇰',
	},
	{
		name: 'Palau',
		code: 'PW',
		languages: ['eng', 'pau'],
		flag: '🇵🇼',
	},
	{
		name: 'Palestine',
		code: 'PS',
		languages: ['ara'],
		flag: '🇵🇸',
	},
	{
		name: 'Panama',
		code: 'PA',
		languages: ['spa'],
		flag: '🇵🇦',
	},
	{
		name: 'Papua New Guinea',
		code: 'PG',
		languages: ['eng', 'hmo', 'tpi'],
		flag: '🇵🇬',
	},
	{
		name: 'Paraguay',
		code: 'PY',
		languages: ['grn', 'spa'],
		flag: '🇵🇾',
	},
	{
		name: 'Peru',
		code: 'PE',
		languages: ['aym', 'que', 'spa'],
		flag: '🇵🇪',
	},
	{
		name: 'Philippines',
		code: 'PH',
		languages: ['eng', 'fil'],
		flag: '🇵🇭',
	},
	{
		name: 'Pitcairn Islands',
		code: 'PN',
		languages: ['eng'],
		flag: '🇵🇳',
	},
	{
		name: 'Poland',
		code: 'PL',
		languages: ['pol'],
		flag: '🇵🇱',
	},
	{
		name: 'Portugal',
		code: 'PT',
		languages: ['por'],
		flag: '🇵🇹',
	},
	{
		name: 'Puerto Rico',
		code: 'PR',
		languages: ['eng', 'spa'],
		flag: '🇵🇷',
	},
	{
		name: 'Qatar',
		code: 'QA',
		languages: ['ara'],
		flag: '🇶🇦',
	},
	{
		name: 'Republic of the Congo',
		code: 'CG',
		languages: ['fra', 'kon', 'lin'],
		flag: '🇨🇬',
	},
	{
		name: 'Romania',
		code: 'RO',
		languages: ['ron'],
		flag: '🇷🇴',
	},
	{
		name: 'Russia',
		code: 'RU',
		languages: ['rus'],
		flag: '🇷🇺',
	},
	{
		name: 'Rwanda',
		code: 'RW',
		languages: ['eng', 'fra', 'kin'],
		flag: '🇷🇼',
	},
	{
		name: 'Reunion',
		code: 'RE',
		languages: ['fra'],
		flag: '🇷🇪',
	},
	{
		name: 'Saint Barthélemy',
		code: 'BL',
		languages: ['fra'],
		flag: '🇧🇱',
	},
	{
		name: 'Saint Helena',
		code: 'SH',
		languages: ['eng'],
		flag: '🇸🇭',
	},
	{
		name: 'Saint Kitts and Nevis',
		code: 'KN',
		languages: ['eng'],
		flag: '🇰🇳',
	},
	{
		name: 'Saint Lucia',
		code: 'LC',
		languages: ['eng'],
		flag: '🇱🇨',
	},
	{
		name: 'Saint Martin',
		code: 'MF',
		languages: ['fra'],
		flag: '🇲🇫',
	},
	{
		name: 'Saint Pierre and Miquelon',
		code: 'PM',
		languages: ['fra'],
		flag: '🇵🇲',
	},
	{
		name: 'Saint Vincent and the Grenadines',
		code: 'VC',
		languages: ['eng'],
		flag: '🇻🇨',
	},
	{
		name: 'Samoa',
		code: 'WS',
		languages: ['eng', 'smo'],
		flag: '🇼🇸',
	},
	{
		name: 'San Marino',
		code: 'SM',
		languages: ['ita'],
		flag: '🇸🇲',
	},
	{
		name: 'Saudi Arabia',
		code: 'SA',
		languages: ['ara'],
		flag: '🇸🇦',
	},
	{
		name: 'Senegal',
		code: 'SN',
		languages: ['fra'],
		flag: '🇸🇳',
	},
	{
		name: 'Serbia',
		code: 'RS',
		languages: ['srp'],
		flag: '🇷🇸',
	},
	{
		name: 'Seychelles',
		code: 'SC',
		languages: ['crs', 'eng', 'fra'],
		flag: '🇸🇨',
	},
	{
		name: 'Sierra Leone',
		code: 'SL',
		languages: ['eng'],
		flag: '🇸🇱',
	},
	{
		name: 'Singapore',
		code: 'SG',
		languages: ['eng', 'msa', 'zho', 'tam'],
		flag: '🇸🇬',
	},
	{
		name: 'Sint Maarten',
		code: 'SX',
		languages: ['eng', 'fra', 'nld'],
		flag: '🇸🇽',
	},
	{
		name: 'Slovakia',
		code: 'SK',
		languages: ['slk', 'ces'],
		flag: '🇸🇰',
	},
	{
		name: 'Slovenia',
		code: 'SI',
		languages: ['slv'],
		flag: '🇸🇮',
	},
	{
		name: 'Solomon Islands',
		code: 'SB',
		languages: ['eng'],
		flag: '🇸🇧',
	},
	{
		name: 'Somalia',
		code: 'SO',
		languages: ['ara', 'som'],
		flag: '🇸🇴',
	},
	{
		name: 'South Africa',
		code: 'ZA',
		languages: ['afr', 'eng', 'nbl', 'nso', 'sot', 'ssw', 'tsn', 'tso', 'ven', 'xho', 'zul'],
		flag: '🇿🇦',
	},
	{
		name: 'South Georgia and the South Sandwich Islands',
		code: 'GS',
		languages: ['eng'],
		flag: '🇬🇸',
	},
	{
		name: 'South Korea',
		code: 'KR',
		languages: ['kor'],
		flag: '🇰🇷',
	},
	{
		name: 'South Sudan',
		code: 'SS',
		languages: ['eng'],
		flag: '🇸🇸',
	},
	{
		name: 'Spain',
		code: 'ES',
		languages: ['spa', 'cat', 'eus', 'glg'],
		flag: '🇪🇸',
	},
	{
		name: 'Sri Lanka',
		code: 'LK',
		languages: ['sin', 'tam'],
		flag: '🇱🇰',
	},
	{
		name: 'Sudan',
		code: 'SD',
		languages: ['ara', 'eng'],
		flag: '🇸🇩',
	},
	{
		name: 'Suriname',
		code: 'SR',
		languages: ['nld'],
		flag: '🇸🇷',
	},
	{
		name: 'Svalbard and Jan Mayen',
		code: 'SJ',
		languages: ['nor'],
		flag: '🇸🇯',
	},
	{
		name: 'Swaziland',
		code: 'SZ',
		languages: ['eng', 'ssw'],
		flag: '🇸🇿',
	},
	{
		name: 'Sweden',
		code: 'SE',
		languages: ['swe'],
		flag: '🇸🇪',
	},
	{
		name: 'Switzerland',
		code: 'CH',
		languages: ['deu', 'fra', 'ita'],
		flag: '🇨🇭',
	},
	{
		name: 'Syria',
		code: 'SY',
		languages: ['ara'],
		flag: '🇸🇾',
	},
	{
		name: 'Sao Tome and Principe',
		code: 'ST',
		languages: ['por'],
		flag: '🇸🇹',
	},
	{
		name: 'Taiwan',
		code: 'TW',
		languages: ['zho'],
		flag: '🇹🇼',
	},
	{
		name: 'Tajikistan',
		code: 'TJ',
		languages: ['rus', 'tgk'],
		flag: '🇹🇯',
	},
	{
		name: 'Tanzania',
		code: 'TZ',
		languages: ['eng', 'swa'],
		flag: '🇹🇿',
	},
	{
		name: 'Thailand',
		code: 'TH',
		languages: ['tha'],
		flag: '🇹🇭',
	},
	{
		name: 'Togo',
		code: 'TG',
		languages: ['fra'],
		flag: '🇹🇬',
	},
	{
		name: 'Tokelau',
		code: 'TK',
		languages: ['eng', 'smo', 'tkl'],
		flag: '🇹🇰',
	},
	{
		name: 'Tonga',
		code: 'TO',
		languages: ['eng', 'ton'],
		flag: '🇹🇴',
	},
	{
		name: 'Trinidad and Tobago',
		code: 'TT',
		languages: ['eng'],
		flag: '🇹🇹',
	},
	{
		name: 'Tunisia',
		code: 'TN',
		languages: ['ara'],
		flag: '🇹🇳',
	},
	{
		name: 'Turkiye',
		code: 'TR',
		languages: ['tur'],
		flag: '🇹🇷',
	},
	{
		name: 'Turkmenistan',
		code: 'TM',
		languages: ['rus', 'tuk'],
		flag: '🇹🇲',
	},
	{
		name: 'Turks and Caicos Islands',
		code: 'TC',
		languages: ['eng'],
		flag: '🇹🇨',
	},
	{
		name: 'Tuvalu',
		code: 'TV',
		languages: ['eng', 'tvl'],
		flag: '🇹🇻',
	},
	{
		name: 'U.S. Minor Outlying Islands',
		code: 'UM',
		languages: ['eng'],
		flag: '🇺🇲',
	},
	{
		name: 'U.S. Virgin Islands',
		code: 'VI',
		languages: ['eng'],
		flag: '🇻🇮',
	},
	{
		name: 'Uganda',
		code: 'UG',
		languages: ['eng', 'swa'],
		flag: '🇺🇬',
	},
	{
		name: 'Ukraine',
		code: 'UA',
		languages: ['ukr'],
		flag: '🇺🇦',
	},
	{
		name: 'United Arab Emirates',
		code: 'AE',
		languages: ['ara'],
		flag: '🇦🇪',
	},
	{
		name: 'United Kingdom',
		code: 'UK',
		languages: ['eng'],
		flag: '🇬🇧',
	},
	{
		name: 'United States',
		code: 'US',
		languages: ['eng', 'spa'],
		flag: '🇺🇸',
	},
	{
		name: 'Uruguay',
		code: 'UY',
		languages: ['spa'],
		flag: '🇺🇾',
	},
	{
		name: 'Uzbekistan',
		code: 'UZ',
		languages: ['rus', 'uzb'],
		flag: '🇺🇿',
	},
	{
		name: 'Vanuatu',
		code: 'VU',
		languages: ['bis', 'eng', 'fra'],
		flag: '🇻🇺',
	},
	{
		name: 'Vatican City',
		code: 'VA',
		languages: ['ita', 'lat'],
		flag: '🇻🇦',
	},
	{
		name: 'Venezuela',
		code: 'VE',
		languages: ['spa'],
		flag: '🇻🇪',
	},
	{
		name: 'Vietnam',
		code: 'VN',
		languages: ['vie'],
		flag: '🇻🇳',
	},
	{
		name: 'Wallis and Futuna',
		code: 'WF',
		languages: ['fra'],
		flag: '🇼🇫',
	},
	{
		name: 'Western Sahara',
		code: 'EH',
		languages: ['zgh', 'mey', 'spa'],
		flag: '🇪🇭',
	},
	{
		name: 'Yemen',
		code: 'YE',
		languages: ['ara'],
		flag: '🇾🇪',
	},
	{
		name: 'Zambia',
		code: 'ZM',
		languages: ['eng'],
		flag: '🇿🇲',
	},
	{
		name: 'Zimbabwe',
		code: 'ZW',
		languages: [
			'bwg',
			'eng',
			'kck',
			'hio',
			'ndc',
			'nde',
			'nya',
			'sna',
			'sot',
			'toi',
			'tsn',
			'tso',
			'ven',
			'xho',
			'zib',
		],
		flag: '🇿🇼',
	},
];

const CATEGORIES = {
	en: [
		{
			id: 'auto',
			name: 'Auto',
			description: 'Programming related to cars, motorcycles, and other automobiles',
		},
		{
			id: 'animation',
			name: 'Animation',
			description: 'Programming is mostly 2D or 3D animation',
		},
		{
			id: 'business',
			name: 'Business',
			description: 'Programming related to business',
		},
		{
			id: 'classic',
			name: 'Classic',
			description: 'Programming is mostly from earlier decades',
		},
		{
			id: 'comedy',
			name: 'Comedy',
			description: 'Programming is mostly comedy',
		},
		{
			id: 'cooking',
			name: 'Cooking',
			description: 'Programs related to cooking or food in general',
		},
		{
			id: 'culture',
			name: 'Culture',
			description: 'Programming is mostly about art and culture',
		},
		{
			id: 'documentary',
			name: 'Documentary',
			description: 'Programming that depicts a person or real-world event',
		},
		{
			id: 'education',
			name: 'Education',
			description: 'Programming is intended to be educational',
		},
		{
			id: 'entertainment',
			name: 'Entertainment',
			description: 'Channels with a variety of entertainment programs',
		},
		{
			id: 'family',
			name: 'Family',
			description: 'Programming that is be suitable for all members of a family',
		},
		{
			id: 'general',
			name: 'General',
			description: 'Provides a variety of different programming',
		},
		{
			id: 'interactive',
			name: 'Interactive',
			description: 'Programming that allows viewers to actively engage with the content',
		},
		{
			id: 'kids',
			name: 'Kids',
			description: 'Programming targeted to children',
		},
		{
			id: 'legislative',
			name: 'Legislative',
			description: 'Programming specific to the operation of government',
		},
		{
			id: 'lifestyle',
			name: 'Lifestyle',
			description: 'Programs related to health, fitness, leisure, fashion, decor, etc.',
		},
		{
			id: 'movies',
			name: 'Movies',
			description: 'Channels that only show movies',
		},
		{
			id: 'music',
			name: 'Music',
			description: 'Programming is music or music related',
		},
		{
			id: 'news',
			name: 'News',
			description: 'Programming is mostly news',
		},
		{
			id: 'outdoor',
			name: 'Outdoor',
			description: 'Programming related to outdoor activities like fishing, hunting, etc.',
		},
		{
			id: 'public',
			name: 'Public',
			description: 'Non-commercial channels that prioritize public service',
		},
		{
			id: 'relax',
			name: 'Relax',
			description: 'Programming is calm sounding and beautiful views',
		},
		{
			id: 'religious',
			name: 'Religious',
			description: 'Religious programming',
		},
		{
			id: 'series',
			name: 'Series',
			description: 'Channels that only show series',
		},
		{
			id: 'science',
			name: 'Science',
			description: 'Science and Technology',
		},
		{
			id: 'shop',
			name: 'Shop',
			description: 'Programming is for shopping',
		},
		{
			id: 'sports',
			name: 'Sports',
			description: 'Programming is sports',
		},
		{
			id: 'travel',
			name: 'Travel',
			description: 'Programming is travel related',
		},
		{
			id: 'weather',
			name: 'Weather',
			description: 'Programming is focused on weather',
		},
		{
			id: 'xxx',
			name: 'XXX',
			description: 'Programming is adult oriented and x-rated',
		},
	],
	es: [
		{
			id: 'auto',
			name: 'Auto',
			description: 'Programacion relacionada con autos, motocicletas y otros vehiculos',
		},
		{
			id: 'animation',
			name: 'Animacion',
			description: 'La programacion es mayormente de animacion 2D o 3D',
		},
		{
			id: 'business',
			name: 'Negocios',
			description: 'Programacion relacionada con negocios',
		},
		{
			id: 'classic',
			name: 'Clasico',
			description: 'La programacion es mayormente de decadas anteriores',
		},
		{
			id: 'comedy',
			name: 'Comedia',
			description: 'La programacion es mayormente de comedia',
		},
		{
			id: 'cooking',
			name: 'Cocina',
			description: 'Programas relacionados con cocina o comida en general',
		},
		{
			id: 'culture',
			name: 'Cultura',
			description: 'La programacion trata mayormente sobre arte y cultura',
		},
		{
			id: 'documentary',
			name: 'Documental',
			description: 'Programacion que muestra una persona o evento del mundo real',
		},
		{
			id: 'education',
			name: 'Educacion',
			description: 'La programacion esta orientada a la educacion',
		},
		{
			id: 'entertainment',
			name: 'Entretenimiento',
			description: 'Canales con variedad de programas de entretenimiento',
		},
		{
			id: 'family',
			name: 'Familia',
			description: 'Programacion adecuada para todos los miembros de la familia',
		},
		{
			id: 'general',
			name: 'General',
			description: 'Ofrece una variedad de programacion diferente',
		},
		{
			id: 'interactive',
			name: 'Interactivo',
			description: 'Programacion que permite a los espectadores participar activamente',
		},
		{
			id: 'kids',
			name: 'Infantil',
			description: 'Programacion dirigida a ninos',
		},
		{
			id: 'legislative',
			name: 'Legislativo',
			description: 'Programacion especifica sobre el funcionamiento del gobierno',
		},
		{
			id: 'lifestyle',
			name: 'Estilo de vida',
			description: 'Programas sobre salud, fitness, ocio, moda, decoracion, etc.',
		},
		{
			id: 'movies',
			name: 'Peliculas',
			description: 'Canales que solo transmiten peliculas',
		},
		{
			id: 'music',
			name: 'Musica',
			description: 'La programacion es musica o relacionada con musica',
		},
		{
			id: 'news',
			name: 'Noticias',
			description: 'La programacion es mayormente noticias',
		},
		{
			id: 'outdoor',
			name: 'Aire libre',
			description: 'Programacion sobre actividades al aire libre como pesca, caza, etc.',
		},
		{
			id: 'public',
			name: 'Publico',
			description: 'Canales no comerciales que priorizan el servicio publico',
		},
		{
			id: 'relax',
			name: 'Relax',
			description: 'Programacion tranquila con sonidos calmados y vistas hermosas',
		},
		{
			id: 'religious',
			name: 'Religioso',
			description: 'Programacion religiosa',
		},
		{
			id: 'series',
			name: 'Series',
			description: 'Canales que solo transmiten series',
		},
		{
			id: 'science',
			name: 'Ciencia',
			description: 'Ciencia y tecnologia',
		},
		{
			id: 'shop',
			name: 'Tienda',
			description: 'Programacion para compras',
		},
		{
			id: 'sports',
			name: 'Deportes',
			description: 'La programacion es deportiva',
		},
		{
			id: 'travel',
			name: 'Viajes',
			description: 'Programacion relacionada con viajes',
		},
		{
			id: 'weather',
			name: 'Clima',
			description: 'La programacion esta enfocada en el clima',
		},
		{
			id: 'xxx',
			name: 'XXX',
			description: 'Programacion para adultos y clasificada X',
		},
	],
	nl: [
		{
			id: 'auto',
			name: 'Auto',
			description: "Programmering gerelateerd aan auto's, motorfietsen en andere voertuigen",
		},
		{
			id: 'animation',
			name: 'Animatie',
			description: 'Programmering is meestal 2D- of 3D-animatie',
		},
		{
			id: 'business',
			name: 'Zakelijk',
			description: 'Programmering gerelateerd aan zaken en bedrijfsleven',
		},
		{
			id: 'classic',
			name: 'Klassiek',
			description: 'Programmering komt meestal uit eerdere decennia',
		},
		{
			id: 'comedy',
			name: 'Komedie',
			description: 'Programmering is meestal komedie',
		},
		{
			id: 'cooking',
			name: 'Koken',
			description: 'Programmas over koken of eten in het algemeen',
		},
		{
			id: 'culture',
			name: 'Cultuur',
			description: 'Programmering gaat vooral over kunst en cultuur',
		},
		{
			id: 'documentary',
			name: 'Documentaire',
			description: 'Programmering die een persoon of gebeurtenis uit de echte wereld toont',
		},
		{
			id: 'education',
			name: 'Educatie',
			description: 'Programmering is bedoeld om educatief te zijn',
		},
		{
			id: 'entertainment',
			name: 'Entertainment',
			description: "Kanalen met een verscheidenheid aan entertainmentprogramma's",
		},
		{
			id: 'family',
			name: 'Familie',
			description: 'Programmering die geschikt is voor alle gezinsleden',
		},
		{
			id: 'general',
			name: 'Algemeen',
			description: 'Biedt een gevarieerde mix van verschillende programmering',
		},
		{
			id: 'interactive',
			name: 'Interactief',
			description: 'Programmering waarbij kijkers actief kunnen deelnemen',
		},
		{
			id: 'kids',
			name: 'Kinderen',
			description: 'Programmering gericht op kinderen',
		},
		{
			id: 'legislative',
			name: 'Wetgevend',
			description: 'Programmering specifiek over de werking van de overheid',
		},
		{
			id: 'lifestyle',
			name: 'Lifestyle',
			description: 'Programmas over gezondheid, fitness, vrije tijd, mode, decoratie, enz.',
		},
		{
			id: 'movies',
			name: 'Films',
			description: 'Kanalen die alleen films uitzenden',
		},
		{
			id: 'music',
			name: 'Muziek',
			description: 'Programmering is muziek of muziekgerelateerd',
		},
		{
			id: 'news',
			name: 'Nieuws',
			description: 'Programmering is meestal nieuws',
		},
		{
			id: 'outdoor',
			name: 'Buiten',
			description: 'Programmering over buitenactiviteiten zoals vissen, jagen, enz.',
		},
		{
			id: 'public',
			name: 'Publiek',
			description: 'Niet-commerciele kanalen die publieke dienstverlening prioriteren',
		},
		{
			id: 'relax',
			name: 'Ontspanning',
			description: 'Rustige programmering met kalme geluiden en mooie uitzichten',
		},
		{
			id: 'religious',
			name: 'Religieus',
			description: 'Religieuze programmering',
		},
		{
			id: 'series',
			name: 'Series',
			description: 'Kanalen die alleen series uitzenden',
		},
		{
			id: 'science',
			name: 'Wetenschap',
			description: 'Wetenschap en technologie',
		},
		{
			id: 'shop',
			name: 'Winkelen',
			description: 'Programmering voor winkelen',
		},
		{
			id: 'sports',
			name: 'Sport',
			description: 'Programmering is sportgericht',
		},
		{
			id: 'travel',
			name: 'Reizen',
			description: 'Programmering gerelateerd aan reizen',
		},
		{
			id: 'weather',
			name: 'Weer',
			description: 'Programmering is gericht op het weer',
		},
		{
			id: 'xxx',
			name: 'XXX',
			description: 'Programmering is voor volwassenen en x-rated',
		},
	],
	fr: [
		{
			id: 'auto',
			name: 'Auto',
			description: 'Programmation liee aux voitures, motos et autres automobiles',
		},
		{
			id: 'animation',
			name: 'Animation',
			description: "La programmation est principalement de l'animation 2D ou 3D",
		},
		{
			id: 'business',
			name: 'Affaires',
			description: 'Programmation liee au monde des affaires',
		},
		{
			id: 'classic',
			name: 'Classique',
			description: 'La programmation provient surtout des decennies precedentes',
		},
		{
			id: 'comedy',
			name: 'Comedie',
			description: 'La programmation est principalement comique',
		},
		{
			id: 'cooking',
			name: 'Cuisine',
			description: 'Programmes lies a la cuisine ou a la nourriture en general',
		},
		{
			id: 'culture',
			name: 'Culture',
			description: "La programmation porte surtout sur l'art et la culture",
		},
		{
			id: 'documentary',
			name: 'Documentaire',
			description: 'Programmation qui depeint une personne ou un evenement reel',
		},
		{
			id: 'education',
			name: 'Education',
			description: 'La programmation est a vocation educative',
		},
		{
			id: 'entertainment',
			name: 'Divertissement',
			description: 'Chaines proposant une variete de programmes de divertissement',
		},
		{
			id: 'family',
			name: 'Famille',
			description: 'Programmation adaptee a tous les membres de la famille',
		},
		{
			id: 'general',
			name: 'General',
			description: 'Propose une grande variete de programmations',
		},
		{
			id: 'interactive',
			name: 'Interactif',
			description: 'Programmation permettant aux spectateurs de participer activement',
		},
		{
			id: 'kids',
			name: 'Enfants',
			description: 'Programmation destinee aux enfants',
		},
		{
			id: 'legislative',
			name: 'Legislatif',
			description: 'Programmation specifique au fonctionnement du gouvernement',
		},
		{
			id: 'lifestyle',
			name: 'Style de vie',
			description: 'Programmes sur la sante, le fitness, les loisirs, la mode, la decoration, etc.',
		},
		{
			id: 'movies',
			name: 'Films',
			description: 'Chaines qui diffusent uniquement des films',
		},
		{
			id: 'music',
			name: 'Musique',
			description: 'La programmation est musicale ou liee a la musique',
		},
		{
			id: 'news',
			name: 'Actualites',
			description: "La programmation est principalement composee d'actualites",
		},
		{
			id: 'outdoor',
			name: 'Plein air',
			description: 'Programmation liee aux activites de plein air comme la peche, la chasse, etc.',
		},
		{
			id: 'public',
			name: 'Public',
			description: 'Chaines non commerciales qui privilegient le service public',
		},
		{
			id: 'relax',
			name: 'Relaxation',
			description: 'Programmation calme avec des sons apaisants et de beaux paysages',
		},
		{
			id: 'religious',
			name: 'Religieux',
			description: 'Programmation religieuse',
		},
		{
			id: 'series',
			name: 'Series',
			description: 'Chaines qui diffusent uniquement des series',
		},
		{
			id: 'science',
			name: 'Science',
			description: 'Science et technologie',
		},
		{
			id: 'shop',
			name: 'Boutique',
			description: 'Programmation dediee au shopping',
		},
		{
			id: 'sports',
			name: 'Sports',
			description: 'La programmation est sportive',
		},
		{
			id: 'travel',
			name: 'Voyage',
			description: 'Programmation liee au voyage',
		},
		{
			id: 'weather',
			name: 'Meteo',
			description: 'La programmation est axee sur la meteo',
		},
		{
			id: 'xxx',
			name: 'XXX',
			description: 'Programmation pour adultes et classee X',
		},
	],
};

export { COUNTRIES, CATEGORIES };
