/**
 * IPTV.org Logo Colors Constant
 * Auto-generated color palette for channel logos
 * Generated by: scripts/build-iptv-logo-colors.ts
 */

export interface LogoColorInfo {
	channel: string;
	logo: {
		width: number;
		height: number;
		aspectRatio: number;
		url: string;
		colors: {
			Vibrant: string | null;
			DarkVibrant: string | null;
			LightVibrant: string | null;
			Muted: string | null;
			DarkMuted: string | null;
			LightMuted: string | null;
		};
		bestBackground: 'light' | 'dark';
	};
}

// Import generated colors from JSON
 
const iptvLogoColors: Record<string, LogoColorInfo> = require('../../generated/iptv-logo-colors.json');

export default iptvLogoColors;
