import * as react_native_reanimated from 'react-native-reanimated';
import * as _legendapp_list_reanimated from '@legendapp/list/reanimated';
import * as _legendapp_list from '@legendapp/list';
import { LegendListRef } from '@legendapp/list';
import * as react_native from 'react-native';
import { Insets } from 'react-native';
import * as React from 'react';

declare const LegendList: <ItemT, ListT extends (<T>(props: Omit<Omit<react_native.ScrollViewProps, "scrollEventThrottle">, "contentOffset" | "contentInset" | "maintainVisibleContentPosition" | "stickyHeaderIndices" | "removeClippedSubviews"> & {
    alignItemsAtEnd?: boolean;
    columnWrapperStyle?: _legendapp_list.ColumnWrapperStyle;
    data: readonly T[];
    drawDistance?: number;
    estimatedItemSize?: number;
    extraData?: any;
    getEstimatedItemSize?: ((index: number, item: T) => number) | undefined;
    initialContainerPoolRatio?: number | undefined;
    initialScrollOffset?: number;
    initialScrollIndex?: number;
    ItemSeparatorComponent?: React.ComponentType<{
        leadingItem: T;
    }> | undefined;
    keyExtractor?: ((item: T, index: number) => string) | undefined;
    ListEmptyComponent?: React.ComponentType<any> | React.ReactElement | null | undefined;
    ListFooterComponent?: React.ComponentType<any> | React.ReactElement | null | undefined;
    ListFooterComponentStyle?: react_native.StyleProp<react_native.ViewStyle> | undefined;
    ListHeaderComponent?: React.ComponentType<any> | React.ReactElement | null | undefined;
    ListHeaderComponentStyle?: react_native.StyleProp<react_native.ViewStyle> | undefined;
    maintainScrollAtEnd?: boolean;
    maintainScrollAtEndThreshold?: number;
    maintainVisibleContentPosition?: boolean;
    numColumns?: number;
    onEndReached?: ((info: {
        distanceFromEnd: number;
    }) => void) | null | undefined;
    onEndReachedThreshold?: number | null | undefined;
    onItemSizeChanged?: ((info: {
        size: number;
        previous: number;
        index: number;
        itemKey: string;
        itemData: T;
    }) => void) | undefined;
    onRefresh?: () => void;
    onStartReached?: ((info: {
        distanceFromStart: number;
    }) => void) | null | undefined;
    onStartReachedThreshold?: number | null | undefined;
    onViewableItemsChanged?: _legendapp_list.OnViewableItemsChanged | undefined;
    progressViewOffset?: number;
    recycleItems?: boolean;
    refScrollView?: React.Ref<react_native.ScrollView>;
    refreshing?: boolean;
    renderItem?: ((props: _legendapp_list.LegendListRenderItemProps<T>) => React.ReactNode) | undefined;
    renderScrollComponent?: (props: react_native.ScrollViewProps) => React.ReactElement<react_native.ScrollViewProps>;
    suggestEstimatedItemSize?: boolean;
    viewabilityConfig?: _legendapp_list.ViewabilityConfig;
    viewabilityConfigCallbackPairs?: _legendapp_list.ViewabilityConfigCallbackPairs | undefined;
    waitForInitialLayout?: boolean;
    onLoad?: (info: {
        elapsedTimeInMs: number;
    }) => void;
} & React.RefAttributes<LegendListRef>) => React.ReactNode) | react_native.Animated.AnimatedComponent<(<T>(props: Omit<Omit<react_native.ScrollViewProps, "scrollEventThrottle">, "contentOffset" | "contentInset" | "maintainVisibleContentPosition" | "stickyHeaderIndices" | "removeClippedSubviews"> & {
    alignItemsAtEnd?: boolean;
    columnWrapperStyle?: _legendapp_list.ColumnWrapperStyle;
    data: readonly T[];
    drawDistance?: number;
    estimatedItemSize?: number;
    extraData?: any;
    getEstimatedItemSize?: ((index: number, item: T) => number) | undefined;
    initialContainerPoolRatio?: number | undefined;
    initialScrollOffset?: number;
    initialScrollIndex?: number;
    ItemSeparatorComponent?: React.ComponentType<{
        leadingItem: T;
    }> | undefined;
    keyExtractor?: ((item: T, index: number) => string) | undefined;
    ListEmptyComponent?: React.ComponentType<any> | React.ReactElement | null | undefined;
    ListFooterComponent?: React.ComponentType<any> | React.ReactElement | null | undefined;
    ListFooterComponentStyle?: react_native.StyleProp<react_native.ViewStyle> | undefined;
    ListHeaderComponent?: React.ComponentType<any> | React.ReactElement | null | undefined;
    ListHeaderComponentStyle?: react_native.StyleProp<react_native.ViewStyle> | undefined;
    maintainScrollAtEnd?: boolean;
    maintainScrollAtEndThreshold?: number;
    maintainVisibleContentPosition?: boolean;
    numColumns?: number;
    onEndReached?: ((info: {
        distanceFromEnd: number;
    }) => void) | null | undefined;
    onEndReachedThreshold?: number | null | undefined;
    onItemSizeChanged?: ((info: {
        size: number;
        previous: number;
        index: number;
        itemKey: string;
        itemData: T;
    }) => void) | undefined;
    onRefresh?: () => void;
    onStartReached?: ((info: {
        distanceFromStart: number;
    }) => void) | null | undefined;
    onStartReachedThreshold?: number | null | undefined;
    onViewableItemsChanged?: _legendapp_list.OnViewableItemsChanged | undefined;
    progressViewOffset?: number;
    recycleItems?: boolean;
    refScrollView?: React.Ref<react_native.ScrollView>;
    refreshing?: boolean;
    renderItem?: ((props: _legendapp_list.LegendListRenderItemProps<T>) => React.ReactNode) | undefined;
    renderScrollComponent?: (props: react_native.ScrollViewProps) => React.ReactElement<react_native.ScrollViewProps>;
    suggestEstimatedItemSize?: boolean;
    viewabilityConfig?: _legendapp_list.ViewabilityConfig;
    viewabilityConfigCallbackPairs?: _legendapp_list.ViewabilityConfigCallbackPairs | undefined;
    waitForInitialLayout?: boolean;
    onLoad?: (info: {
        elapsedTimeInMs: number;
    }) => void;
} & React.RefAttributes<LegendListRef>) => React.ReactNode)> | (<ItemT_1>(props: Omit<_legendapp_list_reanimated.AnimatedLegendListPropsBase<ItemT_1>, "refLegendList"> & {
    getEstimatedItemSize?: ((index: number, item: ItemT_1) => number) | undefined;
    ItemSeparatorComponent?: React.ComponentType<{
        leadingItem: ItemT_1;
    }> | undefined;
    keyExtractor?: ((item: ItemT_1, index: number) => string) | undefined;
    onItemSizeChanged?: ((info: {
        size: number;
        previous: number;
        index: number;
        itemKey: string;
        itemData: ItemT_1;
    }) => void) | undefined;
    renderItem?: ((props: _legendapp_list.LegendListRenderItemProps<ItemT_1>) => React.ReactNode) | undefined;
    animatedProps?: Partial<{
        contentOffset?: react_native.PointProp | react_native_reanimated.SharedValue<react_native.PointProp | undefined> | undefined;
        contentInset?: Insets | react_native_reanimated.SharedValue<Insets | undefined> | undefined;
        maintainVisibleContentPosition?: {
            autoscrollToTopThreshold?: number | null | undefined;
            minIndexForVisible: number;
        } | react_native_reanimated.SharedValue<{
            autoscrollToTopThreshold?: number | null | undefined;
            minIndexForVisible: number;
        } | null | undefined> | null | undefined;
        stickyHeaderIndices?: number[] | react_native_reanimated.SharedValue<number[] | undefined> | undefined;
        removeClippedSubviews?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        scrollEventThrottle?: number | react_native_reanimated.SharedValue<number | undefined> | undefined;
        decelerationRate?: number | "fast" | "normal" | react_native_reanimated.SharedValue<number | "fast" | "normal" | undefined> | undefined;
        horizontal?: boolean | react_native_reanimated.SharedValue<boolean | null | undefined> | null | undefined;
        invertStickyHeaders?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        keyboardDismissMode?: "none" | "interactive" | "on-drag" | react_native_reanimated.SharedValue<"none" | "interactive" | "on-drag" | undefined> | undefined;
        keyboardShouldPersistTaps?: boolean | "always" | "never" | "handled" | react_native_reanimated.SharedValue<boolean | "always" | "never" | "handled" | undefined> | undefined;
        onContentSizeChange?: ((w: number, h: number) => void) | react_native_reanimated.SharedValue<((w: number, h: number) => void) | undefined> | undefined;
        onScroll?: ((event: react_native.NativeSyntheticEvent<react_native.NativeScrollEvent>) => void) | react_native_reanimated.SharedValue<((event: react_native.NativeSyntheticEvent<react_native.NativeScrollEvent>) => void) | undefined> | undefined;
        onScrollBeginDrag?: ((event: react_native.NativeSyntheticEvent<react_native.NativeScrollEvent>) => void) | react_native_reanimated.SharedValue<((event: react_native.NativeSyntheticEvent<react_native.NativeScrollEvent>) => void) | undefined> | undefined;
        onScrollEndDrag?: ((event: react_native.NativeSyntheticEvent<react_native.NativeScrollEvent>) => void) | react_native_reanimated.SharedValue<((event: react_native.NativeSyntheticEvent<react_native.NativeScrollEvent>) => void) | undefined> | undefined;
        onMomentumScrollEnd?: ((event: react_native.NativeSyntheticEvent<react_native.NativeScrollEvent>) => void) | react_native_reanimated.SharedValue<((event: react_native.NativeSyntheticEvent<react_native.NativeScrollEvent>) => void) | undefined> | undefined;
        onMomentumScrollBegin?: ((event: react_native.NativeSyntheticEvent<react_native.NativeScrollEvent>) => void) | react_native_reanimated.SharedValue<((event: react_native.NativeSyntheticEvent<react_native.NativeScrollEvent>) => void) | undefined> | undefined;
        pagingEnabled?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        scrollEnabled?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        showsHorizontalScrollIndicator?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        showsVerticalScrollIndicator?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        stickyHeaderHiddenOnScroll?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        refreshControl?: React.ReactElement<react_native.RefreshControlProps, string | React.JSXElementConstructor<any>> | react_native_reanimated.SharedValue<React.ReactElement<react_native.RefreshControlProps, string | React.JSXElementConstructor<any>> | undefined> | undefined;
        snapToInterval?: number | react_native_reanimated.SharedValue<number | undefined> | undefined;
        snapToOffsets?: number[] | react_native_reanimated.SharedValue<number[] | undefined> | undefined;
        snapToStart?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        snapToEnd?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        disableIntervalMomentum?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        disableScrollViewPanResponder?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        StickyHeaderComponent?: React.ComponentType<any> | react_native_reanimated.SharedValue<React.ComponentType<any> | undefined> | undefined;
        children?: React.ReactNode | react_native_reanimated.SharedValue<React.ReactNode>;
        hitSlop?: number | Insets | react_native_reanimated.SharedValue<number | Insets | null | undefined> | null | undefined;
        id?: string | react_native_reanimated.SharedValue<string | undefined> | undefined;
        needsOffscreenAlphaCompositing?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        onLayout?: ((event: react_native.LayoutChangeEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.LayoutChangeEvent) => void) | undefined> | undefined;
        pointerEvents?: "box-none" | "none" | "box-only" | "auto" | react_native_reanimated.SharedValue<"box-none" | "none" | "box-only" | "auto" | undefined> | undefined;
        testID?: string | react_native_reanimated.SharedValue<string | undefined> | undefined;
        nativeID?: string | react_native_reanimated.SharedValue<string | undefined> | undefined;
        collapsable?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        collapsableChildren?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        renderToHardwareTextureAndroid?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        focusable?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        tabIndex?: 0 | -1 | react_native_reanimated.SharedValue<0 | -1 | undefined> | undefined;
        shouldRasterizeIOS?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        isTVSelectable?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        hasTVPreferredFocus?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        tvParallaxShiftDistanceX?: number | react_native_reanimated.SharedValue<number | undefined> | undefined;
        tvParallaxShiftDistanceY?: number | react_native_reanimated.SharedValue<number | undefined> | undefined;
        tvParallaxTiltAngle?: number | react_native_reanimated.SharedValue<number | undefined> | undefined;
        tvParallaxMagnification?: number | react_native_reanimated.SharedValue<number | undefined> | undefined;
        onStartShouldSetResponder?: ((event: react_native.GestureResponderEvent) => boolean) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => boolean) | undefined> | undefined;
        onMoveShouldSetResponder?: ((event: react_native.GestureResponderEvent) => boolean) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => boolean) | undefined> | undefined;
        onResponderEnd?: ((event: react_native.GestureResponderEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => void) | undefined> | undefined;
        onResponderGrant?: ((event: react_native.GestureResponderEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => void) | undefined> | undefined;
        onResponderReject?: ((event: react_native.GestureResponderEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => void) | undefined> | undefined;
        onResponderMove?: ((event: react_native.GestureResponderEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => void) | undefined> | undefined;
        onResponderRelease?: ((event: react_native.GestureResponderEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => void) | undefined> | undefined;
        onResponderStart?: ((event: react_native.GestureResponderEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => void) | undefined> | undefined;
        onResponderTerminationRequest?: ((event: react_native.GestureResponderEvent) => boolean) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => boolean) | undefined> | undefined;
        onResponderTerminate?: ((event: react_native.GestureResponderEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => void) | undefined> | undefined;
        onStartShouldSetResponderCapture?: ((event: react_native.GestureResponderEvent) => boolean) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => boolean) | undefined> | undefined;
        onMoveShouldSetResponderCapture?: ((event: react_native.GestureResponderEvent) => boolean) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => boolean) | undefined> | undefined;
        onTouchStart?: ((event: react_native.GestureResponderEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => void) | undefined> | undefined;
        onTouchMove?: ((event: react_native.GestureResponderEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => void) | undefined> | undefined;
        onTouchEnd?: ((event: react_native.GestureResponderEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => void) | undefined> | undefined;
        onTouchCancel?: ((event: react_native.GestureResponderEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => void) | undefined> | undefined;
        onTouchEndCapture?: ((event: react_native.GestureResponderEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.GestureResponderEvent) => void) | undefined> | undefined;
        onPointerEnter?: ((event: react_native.PointerEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.PointerEvent) => void) | undefined> | undefined;
        onPointerEnterCapture?: ((event: react_native.PointerEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.PointerEvent) => void) | undefined> | undefined;
        onPointerLeave?: ((event: react_native.PointerEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.PointerEvent) => void) | undefined> | undefined;
        onPointerLeaveCapture?: ((event: react_native.PointerEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.PointerEvent) => void) | undefined> | undefined;
        onPointerMove?: ((event: react_native.PointerEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.PointerEvent) => void) | undefined> | undefined;
        onPointerMoveCapture?: ((event: react_native.PointerEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.PointerEvent) => void) | undefined> | undefined;
        onPointerCancel?: ((event: react_native.PointerEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.PointerEvent) => void) | undefined> | undefined;
        onPointerCancelCapture?: ((event: react_native.PointerEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.PointerEvent) => void) | undefined> | undefined;
        onPointerDown?: ((event: react_native.PointerEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.PointerEvent) => void) | undefined> | undefined;
        onPointerDownCapture?: ((event: react_native.PointerEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.PointerEvent) => void) | undefined> | undefined;
        onPointerUp?: ((event: react_native.PointerEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.PointerEvent) => void) | undefined> | undefined;
        onPointerUpCapture?: ((event: react_native.PointerEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.PointerEvent) => void) | undefined> | undefined;
        accessible?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        accessibilityActions?: readonly Readonly<{
            name: react_native.AccessibilityActionName | string;
            label?: string | undefined;
        }>[] | react_native_reanimated.SharedValue<readonly Readonly<{
            name: react_native.AccessibilityActionName | string;
            label?: string | undefined;
        }>[] | undefined> | undefined;
        accessibilityLabel?: string | react_native_reanimated.SharedValue<string | undefined> | undefined;
        'aria-label'?: string | react_native_reanimated.SharedValue<string | undefined> | undefined;
        accessibilityRole?: react_native.AccessibilityRole | react_native_reanimated.SharedValue<react_native.AccessibilityRole | undefined> | undefined;
        accessibilityState?: react_native.AccessibilityState | react_native_reanimated.SharedValue<react_native.AccessibilityState | undefined> | undefined;
        'aria-busy'?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        'aria-checked'?: boolean | "mixed" | react_native_reanimated.SharedValue<boolean | "mixed" | undefined> | undefined;
        'aria-disabled'?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        'aria-expanded'?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        'aria-selected'?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        accessibilityHint?: string | react_native_reanimated.SharedValue<string | undefined> | undefined;
        accessibilityValue?: react_native.AccessibilityValue | react_native_reanimated.SharedValue<react_native.AccessibilityValue | undefined> | undefined;
        'aria-valuemax'?: number | react_native_reanimated.SharedValue<number | undefined> | undefined;
        'aria-valuemin'?: number | react_native_reanimated.SharedValue<number | undefined> | undefined;
        'aria-valuenow'?: number | react_native_reanimated.SharedValue<number | undefined> | undefined;
        'aria-valuetext'?: string | react_native_reanimated.SharedValue<string | undefined> | undefined;
        onAccessibilityAction?: ((event: react_native.AccessibilityActionEvent) => void) | react_native_reanimated.SharedValue<((event: react_native.AccessibilityActionEvent) => void) | undefined> | undefined;
        importantForAccessibility?: "auto" | "yes" | "no" | "no-hide-descendants" | react_native_reanimated.SharedValue<"auto" | "yes" | "no" | "no-hide-descendants" | undefined> | undefined;
        'aria-hidden'?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        'aria-modal'?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        role?: react_native.Role | react_native_reanimated.SharedValue<react_native.Role | undefined> | undefined;
        accessibilityLabelledBy?: string | string[] | react_native_reanimated.SharedValue<string | string[] | undefined> | undefined;
        'aria-labelledby'?: string | react_native_reanimated.SharedValue<string | undefined> | undefined;
        accessibilityLiveRegion?: "none" | "polite" | "assertive" | react_native_reanimated.SharedValue<"none" | "polite" | "assertive" | undefined> | undefined;
        'aria-live'?: "polite" | "assertive" | "off" | react_native_reanimated.SharedValue<"polite" | "assertive" | "off" | undefined> | undefined;
        accessibilityElementsHidden?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        accessibilityViewIsModal?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        onAccessibilityEscape?: (() => void) | react_native_reanimated.SharedValue<(() => void) | undefined> | undefined;
        onAccessibilityTap?: (() => void) | react_native_reanimated.SharedValue<(() => void) | undefined> | undefined;
        onMagicTap?: (() => void) | react_native_reanimated.SharedValue<(() => void) | undefined> | undefined;
        accessibilityIgnoresInvertColors?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        accessibilityLanguage?: string | react_native_reanimated.SharedValue<string | undefined> | undefined;
        accessibilityShowsLargeContentViewer?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        accessibilityLargeContentTitle?: string | react_native_reanimated.SharedValue<string | undefined> | undefined;
        alwaysBounceHorizontal?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        alwaysBounceVertical?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        automaticallyAdjustContentInsets?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        automaticallyAdjustKeyboardInsets?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        automaticallyAdjustsScrollIndicatorInsets?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        bounces?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        bouncesZoom?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        canCancelContentTouches?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        centerContent?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        contentInsetAdjustmentBehavior?: "always" | "never" | "automatic" | "scrollableAxes" | react_native_reanimated.SharedValue<"always" | "never" | "automatic" | "scrollableAxes" | undefined> | undefined;
        directionalLockEnabled?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        maximumZoomScale?: number | react_native_reanimated.SharedValue<number | undefined> | undefined;
        minimumZoomScale?: number | react_native_reanimated.SharedValue<number | undefined> | undefined;
        onScrollAnimationEnd?: (() => void) | react_native_reanimated.SharedValue<(() => void) | undefined> | undefined;
        pinchGestureEnabled?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        scrollIndicatorInsets?: Insets | react_native_reanimated.SharedValue<Insets | undefined> | undefined;
        scrollToOverflowEnabled?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        scrollsToTop?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        snapToAlignment?: "end" | "start" | "center" | react_native_reanimated.SharedValue<"end" | "start" | "center" | undefined> | undefined;
        onScrollToTop?: ((event: react_native.NativeSyntheticEvent<react_native.NativeScrollEvent>) => void) | react_native_reanimated.SharedValue<((event: react_native.NativeSyntheticEvent<react_native.NativeScrollEvent>) => void) | undefined> | undefined;
        zoomScale?: number | react_native_reanimated.SharedValue<number | undefined> | undefined;
        endFillColor?: react_native.ColorValue | react_native_reanimated.SharedValue<react_native.ColorValue | undefined> | undefined;
        scrollPerfTag?: string | react_native_reanimated.SharedValue<string | undefined> | undefined;
        overScrollMode?: "auto" | "always" | "never" | react_native_reanimated.SharedValue<"auto" | "always" | "never" | undefined> | undefined;
        nestedScrollEnabled?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
        fadingEdgeLength?: number | react_native_reanimated.SharedValue<number | undefined> | undefined;
        persistentScrollbar?: boolean | react_native_reanimated.SharedValue<boolean | undefined> | undefined;
    } & {
        contentContainerStyle?: react_native.StyleProp<react_native_reanimated.AnimatedStyle<react_native.StyleProp<react_native.ViewStyle>>>;
        style?: react_native.StyleProp<react_native_reanimated.AnimatedStyle<react_native.StyleProp<react_native.ViewStyle>>>;
        indicatorStyle?: react_native.StyleProp<react_native_reanimated.AnimatedStyle<"default" | "black" | "white" | undefined>>;
    } & {
        layout?: react_native_reanimated.BaseAnimationBuilder | react_native_reanimated.LayoutAnimationFunction | typeof react_native_reanimated.BaseAnimationBuilder;
        entering?: react_native_reanimated.EntryOrExitLayoutType;
        exiting?: react_native_reanimated.EntryOrExitLayoutType;
    } & {
        sharedTransitionTag?: string;
        sharedTransitionStyle?: react_native_reanimated.SharedTransition;
    }> | undefined;
} & {
    ref?: React.Ref<LegendListRef>;
}) => React.ReactElement | null) = <T>(props: Omit<Omit<react_native.ScrollViewProps, "scrollEventThrottle">, "contentOffset" | "contentInset" | "maintainVisibleContentPosition" | "stickyHeaderIndices" | "removeClippedSubviews"> & {
    alignItemsAtEnd?: boolean;
    columnWrapperStyle?: _legendapp_list.ColumnWrapperStyle;
    data: readonly T[];
    drawDistance?: number;
    estimatedItemSize?: number;
    extraData?: any;
    getEstimatedItemSize?: ((index: number, item: T) => number) | undefined;
    initialContainerPoolRatio?: number | undefined;
    initialScrollOffset?: number;
    initialScrollIndex?: number;
    ItemSeparatorComponent?: React.ComponentType<{
        leadingItem: T;
    }> | undefined;
    keyExtractor?: ((item: T, index: number) => string) | undefined;
    ListEmptyComponent?: React.ComponentType<any> | React.ReactElement | null | undefined;
    ListFooterComponent?: React.ComponentType<any> | React.ReactElement | null | undefined;
    ListFooterComponentStyle?: react_native.StyleProp<react_native.ViewStyle> | undefined;
    ListHeaderComponent?: React.ComponentType<any> | React.ReactElement | null | undefined;
    ListHeaderComponentStyle?: react_native.StyleProp<react_native.ViewStyle> | undefined;
    maintainScrollAtEnd?: boolean;
    maintainScrollAtEndThreshold?: number;
    maintainVisibleContentPosition?: boolean;
    numColumns?: number;
    onEndReached?: ((info: {
        distanceFromEnd: number;
    }) => void) | null | undefined;
    onEndReachedThreshold?: number | null | undefined;
    onItemSizeChanged?: ((info: {
        size: number;
        previous: number;
        index: number;
        itemKey: string;
        itemData: T;
    }) => void) | undefined;
    onRefresh?: () => void;
    onStartReached?: ((info: {
        distanceFromStart: number;
    }) => void) | null | undefined;
    onStartReachedThreshold?: number | null | undefined;
    onViewableItemsChanged?: _legendapp_list.OnViewableItemsChanged | undefined;
    progressViewOffset?: number;
    recycleItems?: boolean;
    refScrollView?: React.Ref<react_native.ScrollView>;
    refreshing?: boolean;
    renderItem?: ((props: _legendapp_list.LegendListRenderItemProps<T>) => React.ReactNode) | undefined;
    renderScrollComponent?: (props: react_native.ScrollViewProps) => React.ReactElement<react_native.ScrollViewProps>;
    suggestEstimatedItemSize?: boolean;
    viewabilityConfig?: _legendapp_list.ViewabilityConfig;
    viewabilityConfigCallbackPairs?: _legendapp_list.ViewabilityConfigCallbackPairs | undefined;
    waitForInitialLayout?: boolean;
    onLoad?: (info: {
        elapsedTimeInMs: number;
    }) => void;
} & React.RefAttributes<LegendListRef>) => React.ReactNode>(props: Omit<Omit<react_native.ScrollViewProps, "scrollEventThrottle">, "contentOffset" | "contentInset" | "maintainVisibleContentPosition" | "stickyHeaderIndices" | "removeClippedSubviews"> & {
    alignItemsAtEnd?: boolean;
    columnWrapperStyle?: _legendapp_list.ColumnWrapperStyle;
    data: readonly ItemT[];
    drawDistance?: number;
    estimatedItemSize?: number;
    extraData?: any;
    getEstimatedItemSize?: ((index: number, item: ItemT) => number) | undefined;
    initialContainerPoolRatio?: number | undefined;
    initialScrollOffset?: number;
    initialScrollIndex?: number;
    ItemSeparatorComponent?: React.ComponentType<{
        leadingItem: ItemT;
    }> | undefined;
    keyExtractor?: ((item: ItemT, index: number) => string) | undefined;
    ListEmptyComponent?: React.ComponentType<any> | React.ReactElement | null | undefined;
    ListFooterComponent?: React.ComponentType<any> | React.ReactElement | null | undefined;
    ListFooterComponentStyle?: react_native.StyleProp<react_native.ViewStyle> | undefined;
    ListHeaderComponent?: React.ComponentType<any> | React.ReactElement | null | undefined;
    ListHeaderComponentStyle?: react_native.StyleProp<react_native.ViewStyle> | undefined;
    maintainScrollAtEnd?: boolean;
    maintainScrollAtEndThreshold?: number;
    maintainVisibleContentPosition?: boolean;
    numColumns?: number;
    onEndReached?: ((info: {
        distanceFromEnd: number;
    }) => void) | null | undefined;
    onEndReachedThreshold?: number | null | undefined;
    onItemSizeChanged?: ((info: {
        size: number;
        previous: number;
        index: number;
        itemKey: string;
        itemData: ItemT;
    }) => void) | undefined;
    onRefresh?: () => void;
    onStartReached?: ((info: {
        distanceFromStart: number;
    }) => void) | null | undefined;
    onStartReachedThreshold?: number | null | undefined;
    onViewableItemsChanged?: _legendapp_list.OnViewableItemsChanged | undefined;
    progressViewOffset?: number;
    recycleItems?: boolean;
    refScrollView?: React.Ref<react_native.ScrollView>;
    refreshing?: boolean;
    renderItem?: ((props: _legendapp_list.LegendListRenderItemProps<ItemT>) => React.ReactNode) | undefined;
    renderScrollComponent?: (props: react_native.ScrollViewProps) => React.ReactElement<react_native.ScrollViewProps>;
    suggestEstimatedItemSize?: boolean;
    viewabilityConfig?: _legendapp_list.ViewabilityConfig;
    viewabilityConfigCallbackPairs?: _legendapp_list.ViewabilityConfigCallbackPairs | undefined;
    waitForInitialLayout?: boolean;
    onLoad?: (info: {
        elapsedTimeInMs: number;
    }) => void;
} & {
    LegendList?: ListT;
} & React.RefAttributes<LegendListRef>) => React.ReactNode;

export { LegendList };
