export const en = {
	// ============ Core Application & Welcome ============
	welcome: 'Welcome',
	toAppName: 'to {{appName}}',
	welcomeTo: 'WELCOME TO {{appName}}',
	welcomeDescription: 'Start browsing our extensive collection of movies and shows today',
	browse: 'Start Browsing',
	finishSetup: 'Finish setup',
	getStarted: 'Get started',
	everyone: 'Everyone',
	goBack: 'Go back',
	anErrorOccurred: 'An error occurred',
	status: 'Status',
	active: 'Active',
	unknown: 'Unknown',
	tryAgainLater: 'Try again later',
	tryAgain: 'Try again',
	loading: 'Loading',
	appInitializing: 'Initializing application',
	backHome: 'Back to home',
	unknownEmail: 'Unknown email address',
	unknownCategory: 'Unknown category',
	internalError: 'Internal error',
	error: 'Error',
	pageNotFound: 'Page Not Found',
	pageNotFoundDesc: 'The page you are looking for does not exist or has been moved.',
	goHome: 'Go to Home',
	errorOccurred: 'An error occurred',
	unknownError: 'An unknown error occurred.',
	retry: 'Retry',
	of: 'of',
	selected: 'selected',
	isSelected: 'is selected',
	unavailable: 'Unavailable',
	categories: 'Categories',
	countries: 'Countries',

	// Player labels
	link: 'Link',
	providers: 'Providers',
	source: 'Source',
	subtitle: 'Subtitle',
	nextEpisode: 'Next Episode',
	reloadSources: 'Reload Sources',
	fetchingSources: 'Fetching video sources...',
	fetchSourcesFailed: 'Failed to fetch video sources',

	// ============ Authentication & Account Management ============
	// -- Account Info --
	currentPassword: 'Current Password',
	newPassword: 'New Password',
	currentCountry: 'Current Country',
	updatingUserInfo: 'Updating user information',
	updatedUserInfo: 'User information updated successfully',
	updatePassword: 'Update Password',
	resetPassword: 'Reset Password',
	resetPasswordDescription: 'Enter your password to reset your account',
	accountInfoDescription: 'Manage your account information, email and password',
	accountInfoLoading: 'Loading your account information...',
	accountInfoFailed: 'Failed to load account information',

	// -- Login/Registration --
	emailRequired: 'Please enter your email address',
	passRequired: 'Please enter your password',
	invalidEmail: 'Invalid email address',
	sendingReset: 'Sending reset email...',
	resetSuccess: 'Reset email sent successfully',
	resetFailed: 'Failed to send reset email',
	register: 'Register',
	login: 'Login',
	fullName: 'Known as',
	email: 'Email',
	password: 'Password',
	logIn: 'Log In',
	forgot: 'Forgot password ?',
	account: "Don't have an account?",
	reset: 'Reset password',
	step1: 'STEP 1 OF 3',
	step2: 'STEP 2 OF 3',
	step3: 'STEP 3 OF 3',
	existedAccount: 'Have an account?',
	agree: 'By signing up, you agree to our',
	month: 'Month',

	// -- AppPlan Actions --
	monthlyPrice: 'Monthly Price',
	switchPlan: 'Switch Plan',
	updateMethod: 'Update Method',
	resubscribe: 'Subscribe Now',
	cancelPlan: 'Cancel Plan',
	pausePlan: 'Pause Plan',
	resumePlan: 'Resume Plan',
	plan: 'Plan',
	billingHistory: 'Billing History',
	lastPayment: 'Last Payment',
	payerId: 'Payer Id',
	paypalAccount: 'Paypal Account',
	billingHistoryDescription: 'A detailed list of all your billed invoices, including dates and amounts.',
	updatePlanMessage: 'By clicking the update method, you will be redirected to the PayPal website.',

	// ============ Subscription Management ============
	// -- General Subscription --
	nextPayment: 'Next Payment',
	expiredAt: 'Expired At',
	cancelledAt: 'Cancelled At',
	validUntil: 'Valid Until',
	pausedAt: 'Paused At',
	loadingSubscription: 'Loading your subscription...',
	loadingDescription:
		'We are currently loading your subscription. If the process fails, please refresh the page and try again.',
	failedSubscription: 'Failed to load your subscription, please try again later.',
	subscriptionUpdated: 'Subscription updated successfully',
	subscriptionNotUpdated: 'Subscription not updated',
	accessCode: 'Access Code',
	accessCodeIssuedBy: 'Issued by',
	accessCodeInfo: 'Access Code Information',
	accessCodeInfoDescription: 'You can buy an access code from our authorized resellers.',
	errorLoadingPlans: 'There was an error loading the plans',
	errorUpdatingPlanStatus: 'An error occurred while updating plan status',
	errorUpdatingPlan: 'An error occurred while updating plan',

	// -- AppPlan Upgrades/Downgrades --
	chooseUpdatePlan: 'Downgrade or Upgrade Plan',
	updatePlanDescription:
		'You can upgrade or downgrade your plan at any time.\n Your new plan will be effective immediately.',
	updatePlan: 'Update Plan',
	checkFailedSubscription: 'Failed to check your subscription',
	createdSubscription: 'Your subscription has been created successfully.',
	checkingSubscription: 'Checking your subscription status...',
	errorCreatingSubscription: 'An error occurred while creating your subscription',
	creatingSubscription: 'Creating your subscription',
	updatingSubscription: 'Updating your subscription',
	updatingSubscriptionDescription:
		'We are currently updating your subscription. If the process fails, please refresh the page and try again.',
	updateFailedSubscription: 'Failed to update subscription',

	// ============ Activation Codes ============
	code: 'Activation Code',
	activationCode: 'Enter your activation Code',
	codeDescription:
		'You can buy an activation code from our authorized resellers.\n Enter the code to activate your account.',
	activateCode: 'New Activation Code',
	activatingCode: 'Activating your code',
	activatingDescription:
		'We are currently activating your code. If the process fails, please refresh the page and try again.',
	activatingWait: 'Activating code, please wait...',
	activationSuccess: 'Activation successful.',
	activationFailed: 'Activation failed, please enter a valid code',
	activationCodeRequired: 'Please enter the activation code',
	activationCodeInvalid: 'Invalid activation code',
	activationAgreement:
		'By activating the code, you agree to our Privacy and Data Policy. You also acknowledge that you have read and understood our Privacy of Service and agree to be bound by them.',

	// ============ Plans & Payments ============
	plans: 'Plans',
	plans4EveryOne: 'Plans for every one',
	plansSubtitle: 'See our Plans and Pricing. Cancel anytime',
	choosePlan: 'Choose Your Plan',
	plansDescription:
		'All plans offer unlimited access to movies, TV shows, and channels.\n Change or cancel your plan at any time.',
	noPlanAvailable: 'No plans available at the moment.',
	loadingPlans: 'Loading plans....',
	failedLoadPlans: 'Failed to load plans!',
	proceedPlan: 'Proceed to payment',
	next: 'Next',
	settingPaymentProcess: 'Setting up your payment process',
	processingPayment: 'Processing your payment',
	processingDescription:
		'We are currently processing your payment. If the process fails, please refresh the page and try again.',
	completedPayment: 'Payment processing completed successfully.',
	paymentFailed: 'Payment processing failed,',
	processingWait: 'Processing payment, please wait...',
	waitRedirected: 'Please wait to be redirected...',
	card: 'Debit or Credit Card',
	setPayment: 'Set up your payment',
	paymentMethod: 'Payment Methods',
	proceedPayment: 'Proceed Payment',
	subscribed: 'Subscribed',
	notSubscribed: 'Not Subscribed',
	subscribeNow: 'Subscribe Now',
	startSubscription: 'Start Subscription',
	renewSubscription: 'Auto-renew subscription',
	renewPlan: 'Auto-renew plan',
	subscriptionNote: 'Start your subscription by choosing payment method and adding the details.',
	recurringPayment: 'Recurring payment',
	recurringPaymentDescription: 'Auto-renew your subscription',
	subAgreement:
		'{{appName}} will automatically continue your membership and charge the membership fee {{price}}/month to your payment method until you cancel. You may cancel at any time to avoid future charges. To cancel automatic renewal of your subscription, go to your profile settings and choose Subscription and disable auto-renew subscription.',
	subAgreementNotAutoRenew:
		'{{appName}} will charge the membership fee {{price}}/month to your payment method until the end of the current billing cycle. Your subscription will not be automatically renewed. To resubscribe, go to your profile settings and choose Subscription.',

	// ============ Content & Media ============
	downloadTitle: 'Enjoy premium content anywhere at minimal cost',
	downloadDescription: 'Stream thousands of Movies, TV shows, and Live Channels in one place',
	planPricing: 'Plan pricing',
	pricingDescription: `No credit card required to get started.\nFlexible monthly plans, cancel anytime.`,
	movies: 'Movies',
	moviesandseries: 'Movies & Series',
	series: 'Series',
	channels: 'Channels',
	search: 'Search',
	favorites: 'Favorites',
	play: 'Play',
	resume: 'Resume',
	continuePlaying: 'Continue Playing',
	searching: 'Searching',
	startSearching: 'Start Searching',
	justMoment: 'Just a moment',
	noResultFound: 'No result found',
	trySearching: 'Try searching for another keyword',
	searchResults: 'Enter a keyword to search for {{type}}',
	genres: 'Genres',
	recommendation: 'Recommendation',
	seasons: 'Seasons',
	episodes: 'Episodes',
	season: 'Season',
	yourFavorites: 'Your Favorites',
	emptyFavorites: 'You have no favorites yet',

	// ============ User Interface ============
	contact: 'Contact us',
	privacy: 'Privacy Policy',
	terms: 'Terms of Use',
	dmca: 'DMCA Policy',
	trademark:
		'This site does not store any files on our server, we only linked to the media which is hosted on 3rd party services.',
	social: 'Follow us',
	copyright: '© 2022 {{appName}}. All rights reserved.',
	noAccount: 'Registrar',
	accountInfo: 'Your Account',
	switchProfile: 'Switch Profile',
	logout: 'Log out',
	managePlan: 'Plan & Billing',
	managePlanDescription: 'Manage your plan, billing and payment methods',
	whoWatching: "Who's watching?",
	editProfile: 'Edit Profile',
	addProfile: 'Add Profile',
	createProfile: 'Add profile',
	manageProfiles: 'Manage Profiles',
	chooseAvatar: 'Choose a avatar',
	deleteProfile: 'Delete profile',
	creatingProfile: 'Creating profile...',
	updatingProfile: 'Updating profile...',
	loadingProfiles: 'Loading profiles...',
	deletingProfile: 'Deleting profile...',
	profileUpdated: 'Profile updated successfully',
	profileCreated: 'Profile created successfully',
	failedDeleteProfile: 'Failed to delete profile',
	profileNameRequired: 'Please enter a profile name',
	profileNotFound: 'Profile not found',
	accountHolderName: 'Account Holder Name',
	displayName: 'Display name',
	autoPlay: 'Autoplay',
	autoPlayNote: 'Automatically play next episode video',
	parentalControls: 'Parental Controls',
	appLanguage: 'App Language',
	cancel: 'Cancel',
	ok: 'Ok',
	no: 'No',
	confirm: 'Confirm',
	done: 'Done',
	save: 'Save Changes',
	delete: 'Delete Profile',
	deleteNote: 'Remove all data associated with this profile',
	deleteNote2: 'All data associated with this profile will be erased',
	updateAccount: 'Update Account',

	// Plans
	deviceSeamlessly: 'Device seamlessly',
	streaming: 'Streaming',

	// Footer
	followUsOn: 'Follow us on',
	links: 'Links',
	contactUs: 'Contact us',
	privacyPolicy: 'Privacy Policy',
	termsOfUse: 'Terms of Use',
	footerTitle: `Enjoy over 1 million+ movies and TV Shows\nWatch each movie online without ads!`,
	footerDisclaimer:
		'{{appName}} does not host any files on our server. All files shared here are collected from the internet from various encoders and hosted on third-party sites. We do not accept responsibility for content hosted on third-party websites. We just index those links which are already available on the internet. If you have any legal issues please contact the content providers and they will take necessary actions.',
} as const;

export type TranslationSchema = {
	[K in keyof typeof en]: string;
};
