// Internal imports
import type { TranslationSchema } from './en';


export const es: TranslationSchema = {
	welcome: 'Bienvenido',
	toAppName: 'a {{appName}}',
	welcomeTo: 'BIENVENIDO A {{appName}}',
	welcomeDescription: 'Empieza a explorar hoy nuestra amplia coleccion de peliculas y series',
	browse: 'Empezar a explorar',
	finishSetup: 'Finalizar configuracion',
	getStarted: 'Comenzar',
	everyone: 'Todos',
	goBack: 'Volver',
	anErrorOccurred: 'Ocurrio un error',
	status: 'Estado',
	active: 'Activo',
	unknown: 'Desconocido',
	tryAgainLater: 'Intentalo de nuevo mas tarde',
	tryAgain: 'Intentar de nuevo',
	loading: 'Cargando',
	appInitializing: 'Inicializando la aplicacion',
	backHome: 'Volver al inicio',
	unknownEmail: 'Direccion de correo desconocida',
	unknownCategory: 'Categoria desconocida',
	internalError: 'Error interno',
	error: 'Error',
	pageNotFound: 'Pagina no encontrada',
	pageNotFoundDesc: 'La pagina que buscas no existe o fue movida.',
	goHome: 'Ir al inicio',
	errorOccurred: 'Ocurrio un error',
	unknownError: 'Ocurrio un error desconocido.',
	retry: 'Reintentar',
	of: 'de',
	selected: 'seleccionado',
	isSelected: 'esta seleccionado',
	unavailable: 'No disponible',
	categories: 'Categorias',
	countries: 'Paises',
	link: 'Enlace',
	providers: 'Proveedores',
	source: 'Fuente',
	subtitle: 'Subtitulo',
	nextEpisode: 'Siguiente episodio',
	reloadSources: 'Recargar fuentes',
	fetchingSources: 'Obteniendo fuentes de video...',
	fetchSourcesFailed: 'No se pudieron obtener las fuentes de video',
	currentPassword: 'Contrasena actual',
	newPassword: 'Nueva contrasena',
	currentCountry: 'Pais actual',
	updatingUserInfo: 'Actualizando la informacion del usuario',
	updatedUserInfo: 'La informacion del usuario se actualizo correctamente',
	updatePassword: 'Actualizar contrasena',
	resetPassword: 'Restablecer contrasena',
	resetPasswordDescription: 'Introduce tu contrasena para restablecer tu cuenta',
	accountInfoDescription: 'Gestiona la informacion de tu cuenta, correo y contrasena',
	accountInfoLoading: 'Cargando la informacion de tu cuenta...',
	accountInfoFailed: 'No se pudo cargar la informacion de la cuenta',
	emailRequired: 'Introduce tu direccion de correo',
	passRequired: 'Introduce tu contrasena',
	invalidEmail: 'Direccion de correo no valida',
	sendingReset: 'Enviando correo de restablecimiento...',
	resetSuccess: 'Correo de restablecimiento enviado correctamente',
	resetFailed: 'No se pudo enviar el correo de restablecimiento',
	register: 'Registrarse',
	login: 'Iniciar sesion',
	fullName: 'Nombre visible',
	email: 'Correo electronico',
	password: 'Contrasena',
	logIn: 'Entrar',
	forgot: 'Olvidaste tu contrasena?',
	account: 'No tienes una cuenta?',
	reset: 'Restablecer contrasena',
	step1: 'PASO 1 DE 3',
	step2: 'PASO 2 DE 3',
	step3: 'PASO 3 DE 3',
	existedAccount: 'Ya tienes una cuenta?',
	agree: 'Al registrarte, aceptas nuestros',
	month: 'Mes',
	monthlyPrice: 'Precio mensual',
	switchPlan: 'Cambiar plan',
	updateMethod: 'Actualizar metodo',
	resubscribe: 'Suscribirse ahora',
	cancelPlan: 'Cancelar plan',
	pausePlan: 'Pausar plan',
	resumePlan: 'Reanudar plan',
	plan: 'Plan',
	billingHistory: 'Historial de facturacion',
	lastPayment: 'Ultimo pago',
	payerId: 'Id del pagador',
	paypalAccount: 'Cuenta de PayPal',
	billingHistoryDescription: 'Una lista detallada de todas tus facturas, incluidas fechas e importes.',
	updatePlanMessage: 'Al hacer clic en actualizar metodo, seras redirigido al sitio web de PayPal.',
	nextPayment: 'Proximo pago',
	expiredAt: 'Expira el',
	cancelledAt: 'Cancelado el',
	validUntil: 'Valido hasta',
	pausedAt: 'Pausado el',
	loadingSubscription: 'Cargando tu suscripcion...',
	loadingDescription:
		'Actualmente estamos cargando tu suscripcion. Si el proceso falla, actualiza la pagina e intentalo de nuevo.',
	failedSubscription: 'No se pudo cargar tu suscripcion, intentalo de nuevo mas tarde.',
	subscriptionUpdated: 'Suscripcion actualizada correctamente',
	subscriptionNotUpdated: 'La suscripcion no se actualizo',
	accessCode: 'Codigo de acceso',
	accessCodeIssuedBy: 'Emitido por',
	accessCodeInfo: 'Informacion del codigo de acceso',
	accessCodeInfoDescription: 'Puedes comprar un codigo de acceso a nuestros revendedores autorizados.',
	errorLoadingPlans: 'Hubo un error al cargar los planes',
	errorUpdatingPlanStatus: 'Ocurrio un error al actualizar el estado del plan',
	errorUpdatingPlan: 'Ocurrio un error al actualizar el plan',
	chooseUpdatePlan: 'Bajar o subir de plan',
	updatePlanDescription:
		'Puedes subir o bajar de plan en cualquier momento.\n Tu nuevo plan sera efectivo inmediatamente.',
	updatePlan: 'Actualizar plan',
	checkFailedSubscription: 'No se pudo comprobar tu suscripcion',
	createdSubscription: 'Tu suscripcion se ha creado correctamente.',
	checkingSubscription: 'Comprobando el estado de tu suscripcion...',
	errorCreatingSubscription: 'Ocurrio un error al crear tu suscripcion',
	creatingSubscription: 'Creando tu suscripcion',
	updatingSubscription: 'Actualizando tu suscripcion',
	updatingSubscriptionDescription:
		'Actualmente estamos actualizando tu suscripcion. Si el proceso falla, actualiza la pagina e intentalo de nuevo.',
	updateFailedSubscription: 'No se pudo actualizar la suscripcion',
	code: 'Codigo de activacion',
	activationCode: 'Introduce tu codigo de activacion',
	codeDescription:
		'Puedes comprar un codigo de activacion a nuestros revendedores autorizados.\n Introduce el codigo para activar tu cuenta.',
	activateCode: 'Activar Código',
	activatingCode: 'Activando tu codigo',
	activatingDescription:
		'Actualmente estamos activando tu codigo. Si el proceso falla, actualiza la pagina e intentalo de nuevo.',
	activatingWait: 'Activando codigo, espera por favor...',
	activationSuccess: 'Activacion correcta.',
	activationFailed: 'La activacion fallo, introduce un codigo valido',
	activationCodeRequired: 'Introduce el codigo de activacion',
	activationCodeInvalid: 'Codigo de activacion no valido',
	activationAgreement:
		'Al activar el codigo, aceptas nuestra Politica de privacidad y datos. Tambien reconoces que has leido y comprendido nuestras Condiciones del servicio y aceptas quedar sujeto a ellas.',
	plans: 'Planes',
	plans4EveryOne: 'Planes para todos',
	plansSubtitle: 'Consulta nuestros planes y precios. Cancela cuando quieras',
	choosePlan: 'Elige tu plan',
	plansDescription:
		'Todos los planes ofrecen acceso ilimitado a peliculas, series y canales.\n Cambia o cancela tu plan en cualquier momento.',
	noPlanAvailable: 'No hay planes disponibles en este momento.',
	loadingPlans: 'Cargando planes....',
	failedLoadPlans: 'No se pudieron cargar los planes!',
	proceedPlan: 'Continuar al pago',
	next: 'Siguiente',
	settingPaymentProcess: 'Preparando tu proceso de pago',
	processingPayment: 'Procesando tu pago',
	processingDescription:
		'Actualmente estamos procesando tu pago. Si el proceso falla, actualiza la pagina e intentalo de nuevo.',
	completedPayment: 'El procesamiento del pago se completo correctamente.',
	paymentFailed: 'El procesamiento del pago fallo,',
	processingWait: 'Procesando el pago, espera por favor...',
	waitRedirected: 'Espera a ser redirigido...',
	card: 'Tarjeta de debito o credito',
	setPayment: 'Configura tu pago',
	paymentMethod: 'Metodos de pago',
	proceedPayment: 'Continuar con el pago',
	subscribed: 'Suscrito',
	notSubscribed: 'No suscrito',
	subscribeNow: 'Suscribirse ahora',
	startSubscription: 'Iniciar suscripcion',
	renewSubscription: 'Renovacion automatica de suscripcion',
	renewPlan: 'Renovacion automatica del plan',
	subscriptionNote: 'Inicia tu suscripcion eligiendo un metodo de pago y agregando los datos.',
	recurringPayment: 'Pago recurrente',
	recurringPaymentDescription: 'Renueva automaticamente tu suscripcion',
	subAgreement:
		'{{appName}} continuara automaticamente tu membresia y cobrara la cuota de membresia de {{price}}/month a tu metodo de pago hasta que canceles. Puedes cancelar en cualquier momento para evitar cargos futuros. Para cancelar la renovacion automatica de tu suscripcion, ve a la configuracion de tu perfil, elige Suscripcion y desactiva la renovacion automatica.',
	subAgreementNotAutoRenew:
		'{{appName}} cobrara la cuota de membresia de {{price}}/month a tu metodo de pago hasta el final del ciclo de facturacion actual. Tu suscripcion no se renovara automaticamente. Para volver a suscribirte, ve a la configuracion de tu perfil y elige Suscripcion.',
	downloadTitle: 'Disfruta contenido premium en cualquier lugar a un costo minimo',
	downloadDescription: 'Transmite miles de peliculas, series y canales en vivo en un solo lugar',
	planPricing: 'Precio del plan',
	pricingDescription: `No necesitas tarjeta de credito para empezar.\nPlanes mensuales flexibles, cancela cuando quieras.`,
	movies: 'Peliculas',
	moviesandseries: 'Peliculas y series',
	series: 'Series',
	channels: 'Canales',
	search: 'Buscar',
	favorites: 'Favoritos',
	play: 'Reproducir',
	resume: 'Reanudar',
	continuePlaying: 'Seguir viendo',
	searching: 'Buscando',
	startSearching: 'Empezar a buscar',
	justMoment: 'Un momento',
	noResultFound: 'No se encontraron resultados',
	trySearching: 'Prueba a buscar con otra palabra clave',
	searchResults: 'Introduce una palabra clave para buscar {{type}}',
	genres: 'Generos',
	recommendation: 'Recomendacion',
	seasons: 'Temporadas',
	episodes: 'Episodios',
	season: 'Temporada',
	yourFavorites: 'Tus favoritos',
	emptyFavorites: 'Todavia no tienes favoritos',
	contact: 'Contactanos',
	privacy: 'Politica de privacidad',
	terms: 'Terminos de uso',
	dmca: 'Politica DMCA',
	trademark:
		'Este sitio no almacena ningun archivo en nuestro servidor, solo enlazamos contenido multimedia alojado en servicios de terceros.',
	social: 'Siguenos',
	copyright: '© 2022 {{appName}}. Todos los derechos reservados.',
	noAccount: 'Registrarse',
	accountInfo: 'Tu cuenta',
	switchProfile: 'Cambiar perfil',
	logout: 'Cerrar sesion',
	managePlan: 'Plan y facturacion',
	managePlanDescription: 'Gestiona tu plan, facturacion y metodos de pago',
	whoWatching: 'Quien esta viendo?',
	editProfile: 'Editar perfil',
	addProfile: 'Agregar perfil',
	createProfile: 'Agregar perfil',
	manageProfiles: 'Gestionar perfiles',
	chooseAvatar: 'Elige un avatar',
	deleteProfile: 'Eliminar perfil',
	creatingProfile: 'Creando perfil...',
	updatingProfile: 'Actualizando perfil...',
	loadingProfiles: 'Cargando perfiles...',
	deletingProfile: 'Eliminando perfil...',
	profileUpdated: 'Perfil actualizado correctamente',
	profileCreated: 'Perfil creado correctamente',
	failedDeleteProfile: 'No se pudo eliminar el perfil',
	profileNameRequired: 'Introduce un nombre de perfil',
	profileNotFound: 'Perfil no encontrado',
	accountHolderName: 'Nombre del titular de la cuenta',
	displayName: 'Nombre visible',
	autoPlay: 'Reproduccion automatica',
	autoPlayNote: 'Reproduce automaticamente el video del siguiente episodio',
	parentalControls: 'Controles parentales',
	appLanguage: 'Idioma de la aplicacion',
	cancel: 'Cancelar',
	ok: 'Aceptar',
	no: 'No',
	confirm: 'Confirmar',
	done: 'Hecho',
	save: 'Guardar cambios',
	delete: 'Eliminar perfil',
	deleteNote: 'Eliminar todos los datos asociados a este perfil',
	deleteNote2: 'Todos los datos asociados a este perfil seran borrados',
	updateAccount: 'Actualizar cuenta',
	deviceSeamlessly: 'Dispositivos sin interrupciones',
	streaming: 'Streaming',
	followUsOn: 'Siguenos en',
	links: 'Enlaces',
	contactUs: 'Contactanos',
	privacyPolicy: 'Politica de privacidad',
	termsOfUse: 'Terminos de uso',
	footerTitle: `Disfruta mas de 1 millon de peliculas y series\nVe cada pelicula online sin anuncios!`,
	footerDisclaimer:
		'{{appName}} no aloja ningun archivo en nuestro servidor. Todos los archivos compartidos aqui se recopilan de internet desde varios codificadores y se alojan en sitios de terceros. No aceptamos responsabilidad por el contenido alojado en sitios web de terceros. Solo indexamos enlaces que ya estan disponibles en internet. Si tienes algun problema legal, contacta con los proveedores del contenido y tomaran las medidas necesarias.',
};
