// Internal imports
import type { TranslationSchema } from './en';


export const fr: TranslationSchema = {
	welcome: 'Bienvenue',
	toAppName: 'sur {{appName}}',
	welcomeTo: 'BIENVENUE SUR {{appName}}',
	welcomeDescription: "Commencez a parcourir notre vaste collection de films et series des aujourd'hui",
	browse: 'Commencer a parcourir',
	finishSetup: 'Terminer la configuration',
	getStarted: 'Commencer',
	everyone: 'Tout le monde',
	goBack: 'Retour',
	anErrorOccurred: 'Une erreur est survenue',
	status: 'Statut',
	active: 'Actif',
	unknown: 'Inconnu',
	tryAgainLater: 'Reessayez plus tard',
	tryAgain: 'Reessayer',
	loading: 'Chargement',
	appInitializing: "Initialisation de l'application",
	backHome: "Retour a l'accueil",
	unknownEmail: 'Adresse e-mail inconnue',
	unknownCategory: 'Categorie inconnue',
	internalError: 'Erreur interne',
	error: 'Erreur',
	pageNotFound: 'Page introuvable',
	pageNotFoundDesc: "La page que vous recherchez n'existe pas ou a ete deplacee.",
	goHome: "Aller a l'accueil",
	errorOccurred: 'Une erreur est survenue',
	unknownError: 'Une erreur inconnue est survenue.',
	retry: 'Reessayer',
	of: 'de',
	selected: 'selectionne',
	isSelected: 'est selectionne',
	unavailable: 'Indisponible',
	categories: 'Categories',
	countries: 'Pays',
	link: 'Lien',
	providers: 'Fournisseurs',
	source: 'Source',
	subtitle: 'Sous-titre',
	nextEpisode: 'Episode suivant',
	reloadSources: 'Recharger les sources',
	fetchingSources: 'Recuperation des sources video...',
	fetchSourcesFailed: 'Echec de la recuperation des sources video',
	currentPassword: 'Mot de passe actuel',
	newPassword: 'Nouveau mot de passe',
	currentCountry: 'Pays actuel',
	updatingUserInfo: 'Mise a jour des informations utilisateur',
	updatedUserInfo: 'Informations utilisateur mises a jour avec succes',
	updatePassword: 'Mettre a jour le mot de passe',
	resetPassword: 'Reinitialiser le mot de passe',
	resetPasswordDescription: 'Saisissez votre mot de passe pour reinitialiser votre compte',
	accountInfoDescription: 'Gerez les informations de votre compte, e-mail et mot de passe',
	accountInfoLoading: 'Chargement des informations de votre compte...',
	accountInfoFailed: 'Echec du chargement des informations du compte',
	emailRequired: 'Veuillez saisir votre adresse e-mail',
	passRequired: 'Veuillez saisir votre mot de passe',
	invalidEmail: 'Adresse e-mail invalide',
	sendingReset: "Envoi de l'e-mail de reinitialisation...",
	resetSuccess: 'E-mail de reinitialisation envoye avec succes',
	resetFailed: "Echec de l'envoi de l'e-mail de reinitialisation",
	register: "S'inscrire",
	login: 'Connexion',
	fullName: 'Nom affiche',
	email: 'E-mail',
	password: 'Mot de passe',
	logIn: 'Se connecter',
	forgot: 'Mot de passe oublie ?',
	account: "Vous n'avez pas de compte ?",
	reset: 'Reinitialiser le mot de passe',
	step1: 'ETAPE 1 SUR 3',
	step2: 'ETAPE 2 SUR 3',
	step3: 'ETAPE 3 SUR 3',
	existedAccount: 'Vous avez deja un compte ?',
	agree: 'En vous inscrivant, vous acceptez nos',
	month: 'Mois',
	monthlyPrice: 'Prix mensuel',
	switchPlan: 'Changer de forfait',
	updateMethod: 'Mettre a jour le moyen',
	resubscribe: "S'abonner maintenant",
	cancelPlan: 'Annuler le forfait',
	pausePlan: 'Suspendre le forfait',
	resumePlan: 'Reprendre le forfait',
	plan: 'Forfait',
	billingHistory: 'Historique de facturation',
	lastPayment: 'Dernier paiement',
	payerId: 'Id du payeur',
	paypalAccount: 'Compte PayPal',
	billingHistoryDescription: 'Une liste detaillee de toutes vos factures, y compris les dates et les montants.',
	updatePlanMessage: 'En cliquant sur mettre a jour le moyen, vous serez redirige vers le site Web de PayPal.',
	nextPayment: 'Prochain paiement',
	expiredAt: 'Expire le',
	cancelledAt: 'Annule le',
	validUntil: "Valide jusqu'au",
	pausedAt: 'Suspendu le',
	loadingSubscription: 'Chargement de votre abonnement...',
	loadingDescription:
		'Nous chargeons actuellement votre abonnement. Si le processus echoue, actualisez la page et reessayez.',
	failedSubscription: 'Echec du chargement de votre abonnement, veuillez reessayer plus tard.',
	subscriptionUpdated: 'Abonnement mis a jour avec succes',
	subscriptionNotUpdated: 'Abonnement non mis a jour',
	accessCode: "Code d'acces",
	accessCodeIssuedBy: 'Delivre par',
	accessCodeInfo: "Informations sur le code d'acces",
	accessCodeInfoDescription: "Vous pouvez acheter un code d'acces aupres de nos revendeurs agrees.",
	errorLoadingPlans: 'Une erreur est survenue lors du chargement des forfaits',
	errorUpdatingPlanStatus: 'Une erreur est survenue lors de la mise a jour du statut du forfait',
	errorUpdatingPlan: 'Une erreur est survenue lors de la mise a jour du forfait',
	chooseUpdatePlan: 'Retrograder ou ameliorer le forfait',
	updatePlanDescription:
		'Vous pouvez ameliorer ou retrograder votre forfait a tout moment.\n Votre nouveau forfait prendra effet immediatement.',
	updatePlan: 'Mettre a jour le forfait',
	checkFailedSubscription: 'Echec de la verification de votre abonnement',
	createdSubscription: 'Votre abonnement a ete cree avec succes.',
	checkingSubscription: 'Verification du statut de votre abonnement...',
	errorCreatingSubscription: 'Une erreur est survenue lors de la creation de votre abonnement',
	creatingSubscription: 'Creation de votre abonnement',
	updatingSubscription: 'Mise a jour de votre abonnement',
	updatingSubscriptionDescription:
		'Nous mettons actuellement a jour votre abonnement. Si le processus echoue, actualisez la page et reessayez.',
	updateFailedSubscription: "Echec de la mise a jour de l'abonnement",
	code: "Code d'activation",
	activationCode: "Saisissez votre code d'activation",
	codeDescription:
		"Vous pouvez acheter un code d'activation aupres de nos revendeurs agrees.\n Saisissez le code pour activer votre compte.",
	activateCode: "Nouveau code d'activation",
	activatingCode: 'Activation de votre code',
	activatingDescription:
		'Nous activons actuellement votre code. Si le processus echoue, actualisez la page et reessayez.',
	activatingWait: 'Activation du code, veuillez patienter...',
	activationSuccess: 'Activation reussie.',
	activationFailed: "L'activation a echoue, veuillez saisir un code valide",
	activationCodeRequired: "Veuillez saisir le code d'activation",
	activationCodeInvalid: "Code d'activation invalide",
	activationAgreement:
		"En activant le code, vous acceptez notre Politique de confidentialite et de donnees. Vous reconnaissez egalement avoir lu et compris nos Conditions de service et acceptez d'etre lie par celles-ci.",
	plans: 'Forfaits',
	plans4EveryOne: 'Des forfaits pour tous',
	plansSubtitle: 'Consultez nos forfaits et tarifs. Annulez a tout moment',
	choosePlan: 'Choisissez votre forfait',
	plansDescription:
		'Tous les forfaits offrent un acces illimite aux films, series TV et chaines.\n Modifiez ou annulez votre forfait a tout moment.',
	noPlanAvailable: 'Aucun forfait disponible pour le moment.',
	loadingPlans: 'Chargement des forfaits....',
	failedLoadPlans: 'Echec du chargement des forfaits !',
	proceedPlan: 'Passer au paiement',
	next: 'Suivant',
	settingPaymentProcess: 'Configuration de votre processus de paiement',
	processingPayment: 'Traitement de votre paiement',
	processingDescription:
		'Nous traitons actuellement votre paiement. Si le processus echoue, actualisez la page et reessayez.',
	completedPayment: "Le traitement du paiement s'est termine avec succes.",
	paymentFailed: 'Le traitement du paiement a echoue,',
	processingWait: 'Traitement du paiement, veuillez patienter...',
	waitRedirected: 'Veuillez patienter pendant la redirection...',
	card: 'Carte de debit ou de credit',
	setPayment: 'Configurez votre paiement',
	paymentMethod: 'Moyens de paiement',
	proceedPayment: 'Continuer le paiement',
	subscribed: 'Abonne',
	notSubscribed: 'Non abonne',
	subscribeNow: "S'abonner maintenant",
	startSubscription: "Commencer l'abonnement",
	renewSubscription: "Renouvellement automatique de l'abonnement",
	renewPlan: 'Renouvellement automatique du forfait',
	subscriptionNote: 'Commencez votre abonnement en choisissant un moyen de paiement et en ajoutant les informations.',
	recurringPayment: 'Paiement recurrent',
	recurringPaymentDescription: 'Renouvelez automatiquement votre abonnement',
	subAgreement:
		"{{appName}} poursuivra automatiquement votre adhesion et debitera les frais d'adhesion de {{price}}/month sur votre moyen de paiement jusqu'a votre annulation. Vous pouvez annuler a tout moment pour eviter de futurs frais. Pour annuler le renouvellement automatique de votre abonnement, allez dans les parametres de votre profil, choisissez Abonnement et desactivez le renouvellement automatique.",
	subAgreementNotAutoRenew:
		"{{appName}} debitera les frais d'adhesion de {{price}}/month sur votre moyen de paiement jusqu'a la fin du cycle de facturation en cours. Votre abonnement ne sera pas renouvele automatiquement. Pour vous reabonner, allez dans les parametres de votre profil et choisissez Abonnement.",
	downloadTitle: 'Profitez de contenus premium partout a moindre cout',
	downloadDescription: 'Diffusez des milliers de films, series TV et chaines en direct au meme endroit',
	planPricing: 'Tarification des forfaits',
	pricingDescription: `Aucune carte de credit requise pour commencer.\nForfaits mensuels flexibles, annulez a tout moment.`,
	movies: 'Films',
	moviesandseries: 'Films et series',
	series: 'Series',
	channels: 'Chaines',
	search: 'Recherche',
	favorites: 'Favoris',
	play: 'Lire',
	resume: 'Reprendre',
	continuePlaying: 'Continuer la lecture',
	searching: 'Recherche en cours',
	startSearching: 'Commencer la recherche',
	justMoment: 'Un instant',
	noResultFound: 'Aucun resultat trouve',
	trySearching: 'Essayez un autre mot-cle',
	searchResults: 'Saisissez un mot-cle pour rechercher {{type}}',
	genres: 'Genres',
	recommendation: 'Recommandation',
	seasons: 'Saisons',
	episodes: 'Episodes',
	season: 'Saison',
	yourFavorites: 'Vos favoris',
	emptyFavorites: "Vous n'avez pas encore de favoris",
	contact: 'Contactez-nous',
	privacy: 'Politique de confidentialite',
	terms: "Conditions d'utilisation",
	dmca: 'Politique DMCA',
	trademark:
		'Ce site ne stocke aucun fichier sur notre serveur, nous faisons uniquement des liens vers des medias heberges par des services tiers.',
	social: 'Suivez-nous',
	copyright: '© 2022 {{appName}}. Tous droits reserves.',
	noAccount: "S'inscrire",
	accountInfo: 'Votre compte',
	switchProfile: 'Changer de profil',
	logout: 'Se deconnecter',
	managePlan: 'Forfait et facturation',
	managePlanDescription: 'Gerez votre forfait, la facturation et les moyens de paiement',
	whoWatching: 'Qui regarde ?',
	editProfile: 'Modifier le profil',
	addProfile: 'Ajouter un profil',
	createProfile: 'Ajouter un profil',
	manageProfiles: 'Gerer les profils',
	chooseAvatar: 'Choisissez un avatar',
	deleteProfile: 'Supprimer le profil',
	creatingProfile: 'Creation du profil...',
	updatingProfile: 'Mise a jour du profil...',
	loadingProfiles: 'Chargement des profils...',
	deletingProfile: 'Suppression du profil...',
	profileUpdated: 'Profil mis a jour avec succes',
	profileCreated: 'Profil cree avec succes',
	failedDeleteProfile: 'Echec de la suppression du profil',
	profileNameRequired: 'Veuillez saisir un nom de profil',
	profileNotFound: 'Profil introuvable',
	accountHolderName: 'Nom du titulaire du compte',
	displayName: 'Nom affiche',
	autoPlay: 'Lecture automatique',
	autoPlayNote: "Lire automatiquement la video de l'episode suivant",
	parentalControls: 'Controle parental',
	appLanguage: "Langue de l'application",
	cancel: 'Annuler',
	ok: 'Ok',
	no: 'Non',
	confirm: 'Confirmer',
	done: 'Termine',
	save: 'Enregistrer les modifications',
	delete: 'Supprimer le profil',
	deleteNote: 'Supprimer toutes les donnees associees a ce profil',
	deleteNote2: 'Toutes les donnees associees a ce profil seront effacees',
	updateAccount: 'Mettre a jour le compte',
	deviceSeamlessly: 'Appareils sans interruption',
	streaming: 'Streaming',
	followUsOn: 'Suivez-nous sur',
	links: 'Liens',
	contactUs: 'Contactez-nous',
	privacyPolicy: 'Politique de confidentialite',
	termsOfUse: "Conditions d'utilisation",
	footerTitle: `Profitez de plus d\'1 million de films et series TV\nRegardez chaque film en ligne sans publicites !`,
	footerDisclaimer:
		"{{appName}} n'heberge aucun fichier sur notre serveur. Tous les fichiers partages ici sont collectes sur internet depuis diverses sources et heberges sur des sites tiers. Nous n'acceptons aucune responsabilite pour le contenu heberge sur des sites tiers. Nous indexons simplement des liens deja disponibles sur internet. Si vous avez des problemes juridiques, veuillez contacter les fournisseurs de contenu et ils prendront les mesures necessaires.",
};
