// Internal imports
import type { TranslationSchema } from './en';


export const nl: TranslationSchema = {
	welcome: 'Welkom',
	toAppName: 'bij {{appName}}',
	welcomeTo: 'WELKOM BIJ {{appName}}',
	welcomeDescription: 'Begin vandaag nog met bladeren door onze uitgebreide collectie films en series',
	browse: 'Begin met bladeren',
	finishSetup: 'Installatie voltooien',
	getStarted: 'Aan de slag',
	everyone: 'Iedereen',
	goBack: 'Ga terug',
	anErrorOccurred: 'Er is een fout opgetreden',
	status: 'Status',
	active: 'Actief',
	unknown: 'Onbekend',
	tryAgainLater: 'Probeer het later opnieuw',
	tryAgain: 'Probeer opnieuw',
	loading: 'Laden',
	appInitializing: 'Applicatie wordt geinitialiseerd',
	initializingServer: 'Services worden geinitialiseerd',
	authenticatingUser: 'Gebruiker wordt geverifieerd',
	backHome: 'Terug naar home',
	unknownEmail: 'Onbekend e-mailadres',
	unknownCategory: 'Onbekende categorie',
	internalError: 'Interne fout',
	error: 'Fout',
	pageNotFound: 'Pagina niet gevonden',
	pageNotFoundDesc: 'De pagina die je zoekt bestaat niet of is verplaatst.',
	goHome: 'Ga naar home',
	errorOccurred: 'Er is een fout opgetreden',
	unknownError: 'Er is een onbekende fout opgetreden.',
	retry: 'Opnieuw proberen',
	of: 'van',
	selected: 'geselecteerd',
	isSelected: 'is geselecteerd',
	unavailable: 'Niet beschikbaar',
	categories: 'Categorieen',
	countries: 'Landen',
	link: 'Link',
	providers: 'Providers',
	source: 'Bron',
	subtitle: 'Ondertitel',
	nextEpisode: 'Volgende aflevering',
	reloadSources: 'Bronnen opnieuw laden',
	fetchingSources: 'Videobronnen ophalen...',
	fetchSourcesFailed: 'Ophalen van videobronnen mislukt',
	serverInitializationTimeout: 'Verbindingstijdslimiet verlopen',
	serverInitializationTimeoutDesc:
		'Kan de services niet bereiken. Controleer uw internetverbinding en probeer het opnieuw.',
	currentPassword: 'Huidig wachtwoord',
	newPassword: 'Nieuw wachtwoord',
	currentCountry: 'Huidig land',
	updatingUserInfo: 'Gebruikersinformatie wordt bijgewerkt',
	updatedUserInfo: 'Gebruikersinformatie succesvol bijgewerkt',
	updatePassword: 'Wachtwoord bijwerken',
	resetPassword: 'Wachtwoord resetten',
	resetPasswordDescription: 'Voer je wachtwoord in om je account te resetten',
	accountInfoDescription: 'Beheer je accountgegevens, e-mail en wachtwoord',
	accountInfoLoading: 'Je accountgegevens worden geladen...',
	accountInfoFailed: 'Laden van accountgegevens mislukt',
	emailRequired: 'Voer je e-mailadres in',
	passRequired: 'Voer je wachtwoord in',
	invalidEmail: 'Ongeldig e-mailadres',
	sendingReset: 'Reset e-mail wordt verzonden...',
	resetSuccess: 'Reset e-mail succesvol verzonden',
	resetFailed: 'Verzenden van reset e-mail mislukt',
	register: 'Registreren',
	login: 'Inloggen',
	fullName: 'Bekend als',
	email: 'E-mail',
	password: 'Wachtwoord',
	logIn: 'Log in',
	forgot: 'Wachtwoord vergeten?',
	account: 'Heb je geen account?',
	reset: 'Wachtwoord resetten',
	step1: 'STAP 1 VAN 3',
	step2: 'STAP 2 VAN 3',
	step3: 'STAP 3 VAN 3',
	existedAccount: 'Heb je al een account?',
	agree: 'Door je aan te melden ga je akkoord met onze',
	month: 'Maand',
	monthlyPrice: 'Maandprijs',
	switchPlan: 'Plan wijzigen',
	updateMethod: 'Methode bijwerken',
	resubscribe: 'Nu abonneren',
	cancelPlan: 'Plan annuleren',
	pausePlan: 'Plan pauzeren',
	resumePlan: 'Plan hervatten',
	plan: 'Plan',
	billingHistory: 'Factuurgeschiedenis',
	lastPayment: 'Laatste betaling',
	payerId: 'Betaler-id',
	paypalAccount: 'PayPal-account',
	billingHistoryDescription: 'Een gedetailleerde lijst van al je gefactureerde facturen, inclusief datums en bedragen.',
	updatePlanMessage: 'Als je op methode bijwerken klikt, word je doorgestuurd naar de PayPal-website.',
	nextPayment: 'Volgende betaling',
	expiredAt: 'Verlopen op',
	cancelledAt: 'Geannuleerd op',
	validUntil: 'Geldig tot',
	pausedAt: 'Gepauzeerd op',
	loadingSubscription: 'Je abonnement wordt geladen...',
	loadingDescription:
		'We laden momenteel je abonnement. Als het proces mislukt, vernieuw dan de pagina en probeer het opnieuw.',
	failedSubscription: 'Je abonnement kon niet worden geladen, probeer het later opnieuw.',
	subscriptionUpdated: 'Abonnement succesvol bijgewerkt',
	subscriptionNotUpdated: 'Abonnement niet bijgewerkt',
	accessCode: 'Toegangscode',
	accessCodeIssuedBy: 'Uitgegeven door',
	accessCodeInfo: 'Informatie over toegangscode',
	accessCodeInfoDescription: 'Je kunt een toegangscode kopen bij onze geautoriseerde verkopers.',
	errorLoadingPlans: 'Er is een fout opgetreden bij het laden van de plannen',
	errorUpdatingPlanStatus: 'Er is een fout opgetreden bij het bijwerken van de planstatus',
	errorUpdatingPlan: 'Er is een fout opgetreden bij het bijwerken van het plan',
	chooseUpdatePlan: 'Plan downgraden of upgraden',
	updatePlanDescription: 'Je kunt je plan op elk moment upgraden of downgraden.\n Je nieuwe plan gaat onmiddellijk in.',
	updatePlan: 'Plan bijwerken',
	checkFailedSubscription: 'Controleren van je abonnement is mislukt',
	createdSubscription: 'Je abonnement is succesvol aangemaakt.',
	checkingSubscription: 'De status van je abonnement wordt gecontroleerd...',
	errorCreatingSubscription: 'Er is een fout opgetreden bij het aanmaken van je abonnement',
	creatingSubscription: 'Je abonnement wordt aangemaakt',
	updatingSubscription: 'Je abonnement wordt bijgewerkt',
	updatingSubscriptionDescription:
		'We werken momenteel je abonnement bij. Als het proces mislukt, vernieuw dan de pagina en probeer het opnieuw.',
	updateFailedSubscription: 'Bijwerken van abonnement mislukt',
	samePlanSelected: 'Kies alstublieft een ander plan om door te gaan.',
	code: 'Activeringscode',
	activationCode: 'Voer je activeringscode in',
	codeDescription:
		'Je kunt een activeringscode kopen bij onze geautoriseerde verkopers.\n Voer de code in om je account te activeren.',
	activateCode: 'Code activeren',
	activatingCode: 'Je code wordt geactiveerd',
	activatingDescription:
		'We zijn momenteel je code aan het activeren. Als het proces mislukt, vernieuw dan de pagina en probeer het opnieuw.',
	activatingWait: 'Code wordt geactiveerd, even geduld...',
	activationSuccess: 'Activering geslaagd.',
	activationFailed: 'Activering mislukt, voer een geldige code in',
	activationCodeRequired: 'Voer de activeringscode in',
	activationCodeInvalid: 'Ongeldige activeringscode',
	activationAgreement:
		'Door de code te activeren, ga je akkoord met ons Privacy- en databeleid. Je erkent ook dat je onze Servicevoorwaarden hebt gelezen en begrepen en ermee akkoord gaat eraan gebonden te zijn.',
	plans: 'Plannen',
	plans4EveryOne: 'Plannen voor iedereen',
	plansSubtitle: 'Bekijk onze plannen en prijzen. Annuleer op elk moment',
	choosePlan: 'Kies je plan',
	plansDescription:
		'Alle plannen bieden onbeperkte toegang tot films, tv-series en kanalen.\n Wijzig of annuleer je plan op elk moment.',
	noPlanAvailable: 'Er zijn momenteel geen plannen beschikbaar.',
	loadingPlans: 'Plannen laden....',
	failedLoadPlans: 'Laden van plannen mislukt!',
	proceedPlan: 'Doorgaan naar betaling',
	next: 'Volgende',
	settingPaymentProcess: 'Je betaalproces wordt ingesteld',
	processingPayment: 'Je betaling wordt verwerkt',
	processingDescription:
		'We verwerken momenteel je betaling. Als het proces mislukt, vernieuw dan de pagina en probeer het opnieuw.',
	completedPayment: 'Betalingsverwerking succesvol voltooid.',
	paymentFailed: 'Betalingsverwerking mislukt,',
	processingWait: 'Betaling wordt verwerkt, even geduld...',
	waitRedirected: 'Wacht tot je wordt doorgestuurd...',
	redirectingPage: 'Doorsturen',
	redirectingPageDescription: 'Je wordt doorgestuurd naar de juiste pagina. Dit duurt slechts een moment.',
	redirectingWait: 'Doorsturen, even geduld...',
	redirectFailed: 'Doorsturen mislukt, de bestemming is ongeldig.',
	openingApp: 'De app wordt geopend...',
	card: 'Debet- of creditcard',
	setPayment: 'Stel je betaling in',
	paymentMethod: 'Betaalmethoden',
	proceedPayment: 'Doorgaan met betalen',
	subscribed: 'Geabonneerd',
	notSubscribed: 'Niet geabonneerd',
	subscribeNow: 'Nu abonneren',
	startSubscription: 'Abonnement starten',
	renewSubscription: 'Abonnement automatisch verlengen',
	renewPlan: 'Plan automatisch verlengen',
	subscriptionNote: 'Start je abonnement door een betaalmethode te kiezen en de gegevens toe te voegen.',
	recurringPayment: 'Terugkerende betaling',
	recurringPaymentDescription: 'Verleng je abonnement automatisch',
	subAgreement:
		'{{appName}} zal je lidmaatschap automatisch voortzetten en de lidmaatschapskosten van {{price}}/month in rekening brengen op je betaalmethode totdat je opzegt. Je kunt op elk moment opzeggen om toekomstige kosten te voorkomen. Om automatische verlenging van je abonnement te annuleren, ga je naar je profielinstellingen, kies je Abonnement en schakel je automatische verlenging uit.',
	subAgreementNotAutoRenew:
		'{{appName}} brengt de lidmaatschapskosten van {{price}}/month in rekening op je betaalmethode tot het einde van de huidige factureringscyclus. Je abonnement wordt niet automatisch verlengd. Ga naar je profielinstellingen en kies Abonnement om je opnieuw te abonneren.',
	downloadTitle: 'Geniet overal van premium content tegen minimale kosten',
	downloadDescription: 'Stream duizenden films, tv-series en livekanalen op een plek',
	planPricing: 'Planprijzen',
	pricingDescription: `Geen creditcard nodig om te beginnen.\nFlexibele maandplannen, op elk moment opzegbaar.`,
	movies: 'Films',
	moviesandseries: 'Films en series',
	series: 'Series',
	channels: 'Kanalen',
	search: 'Zoeken',
	favorites: 'Favorieten',
	play: 'Afspelen',
	resume: 'Hervatten',
	continuePlaying: 'Verder kijken',
	searching: 'Zoeken',
	startSearching: 'Begin met zoeken',
	justMoment: 'Een ogenblik',
	noResultFound: 'Geen resultaten gevonden',
	trySearching: 'Probeer een ander zoekwoord',
	searchResults: 'Voer een zoekwoord in om te zoeken naar {{type}}',
	genres: 'Genres',
	recommendation: 'Aanbeveling',
	seasons: 'Seizoenen',
	episodes: 'Afleveringen',
	season: 'Seizoen',
	yourFavorites: 'Jouw favorieten',
	emptyFavorites: 'Je hebt nog geen favorieten',
	contact: 'Neem contact op',
	privacy: 'Privacybeleid',
	terms: 'Gebruiksvoorwaarden',
	dmca: 'DMCA-beleid',
	trademark:
		'Deze site slaat geen bestanden op onze server op; we linken alleen naar media die wordt gehost op diensten van derden.',
	social: 'Volg ons',
	copyright: '© 2022 {{appName}}. Alle rechten voorbehouden.',
	noAccount: 'Registreren',
	accountInfo: 'Je account',
	switchProfile: 'Profiel wisselen',
	logout: 'Uitloggen',
	managePlan: 'Plan en facturatie',
	managePlanDescription: 'Beheer je plan, facturatie en betaalmethoden',
	whoWatching: 'Wie kijkt er?',
	editProfile: 'Profiel bewerken',
	addProfile: 'Profiel toevoegen',
	createProfile: 'Profiel toevoegen',
	manageProfiles: 'Profielen beheren',
	chooseAvatar: 'Kies een avatar',
	deleteProfile: 'Profiel verwijderen',
	creatingProfile: 'Profiel wordt aangemaakt...',
	updatingProfile: 'Profiel wordt bijgewerkt...',
	loadingProfiles: 'Profielen worden geladen...',
	deletingProfile: 'Profiel wordt verwijderd...',
	profileUpdated: 'Profiel succesvol bijgewerkt',
	profileCreated: 'Profiel succesvol aangemaakt',
	failedDeleteProfile: 'Profiel verwijderen mislukt',
	profileNameRequired: 'Voer een profielnaam in',
	profileNotFound: 'Profiel niet gevonden',
	accountHolderName: 'Naam van rekeninghouder',
	displayName: 'Weergavenaam',
	autoPlay: 'Automatisch afspelen',
	autoPlayNote: 'Speel automatisch de volgende aflevering af',
	parentalControls: 'Ouderlijk toezicht',
	appLanguage: 'App-taal',
	cancel: 'Annuleren',
	ok: 'Ok',
	no: 'Nee',
	confirm: 'Bevestigen',
	done: 'Klaar',
	save: 'Wijzigingen opslaan',
	delete: 'Profiel verwijderen',
	deleteNote: 'Verwijder alle gegevens die aan dit profiel zijn gekoppeld',
	deleteNote2: 'Alle gegevens die aan dit profiel zijn gekoppeld worden gewist',
	updateAccount: 'Account bijwerken',
	deviceSeamlessly: 'Naadloos op apparaten',
	streaming: 'Streaming',
	followUsOn: 'Volg ons op',
	links: 'Links',
	contactUs: 'Neem contact op',
	privacyPolicy: 'Privacybeleid',
	termsOfUse: 'Gebruiksvoorwaarden',
	footerTitle: `Geniet van meer dan 1 miljoen films en tv-series\nBekijk elke film online zonder advertenties!`,
	footerDisclaimer:
		'{{appName}} host geen bestanden op onze server. Alle bestanden die hier worden gedeeld zijn verzameld van internet uit verschillende bronnen en worden gehost op websites van derden. Wij aanvaarden geen verantwoordelijkheid voor inhoud die wordt gehost op websites van derden. Wij indexeren alleen links die al op internet beschikbaar zijn. Als je juridische problemen hebt, neem dan contact op met de contentproviders; zij zullen de nodige acties ondernemen.',
};
